#!/usr/bin/env python3
"""Validate the focr skill folder."""

from __future__ import annotations

import re
import sys
from pathlib import Path


REQUIRED_REFS = [
    "CLI.md",
    "LIBRARY.md",
    "ROBOT.md",
    "ARTIFACTS-AND-ENV.md",
    "ARCHITECTURE.md",
    "MODEL-AND-KERNELS.md",
    "FOCRQ.md",
    "VERIFICATION.md",
    "DEVELOPMENT.md",
    "BEADS-REALITY.md",
    "TROUBLESHOOTING.md",
    "OPERATORS.md",
    "RESEARCH.md",
]

FORBIDDEN_PATTERNS = [
    (r"focr convert\s+--source", "convert uses positional input, not --source"),
    (r"focr convert[\s\S]{0,240}--tokenizer", "convert has no --tokenizer flag"),
    (r"focr convert[\s\S]{0,240}--out\b", "convert uses -o/--output, not --out"),
    (r"(?m)^\s*focr convert[^\n]*(?:\n(?!```).*){0,8}\n\s*--quant f32\b", "convert has no --quant f32; use focr pull tromr --quant f32 for the TrOMR reference artifact"),
    (r"(?m)^\s*focr convert[^\n]*(?:\n(?!```).*){0,8}\n\s*-o[^\n]*tromr\.focrq[^\n]*(?:\n(?!```).*){0,8}\n\s*--quant int8\b", "TrOMR int8 conversion examples should write tromr.int8.focrq, not tromr.focrq"),
    (r"focr convert --model-id tromr[^.\n]*(?:writes|produces)[^.\n]*tromr\.focrq", "current TrOMR convert is the int8 storage path; f32 tromr.focrq is a pull/preverified reference artifact"),
    (r"tromr\.focrq/tromr\.int8\.focrq depending on requested quant|depending on requested quant[^.\n]*tromr", "current convert does not have a f32 mode; distinguish pull quant selection from convert"),
    (r"`--quant f32`\s+installs\s+`tromr\.focrq`|while\s+`--quant f32`|with\s+`--quant f32`\s+for\s+`tromr\.focrq`|behind\s+`--quant f32`", "spell out focr pull tromr --quant f32 so agents do not attach f32 to convert"),
    (r"focr robot run[^\n]*--json", "robot run is already NDJSON and has no --json flag"),
    (r"ocr[^\n]*--timeout", "ocr has no --timeout flag; use stage-budget env vars"),
    (r"no current `focr pull`", "pull is now implemented"),
    (r"no current `robot selftest`", "robot selftest is now implemented"),
    (r"image-only at the CLI boundary", "native scanned-PDF input is now supported"),
    (r"current v1 CLI input is image-only", "native scanned-PDF input is now supported"),
    (r"PDF rasterization (?:remains|is) out of band", "native scanned-PDF input is now supported"),
    (r"PDFs are rasterized before `focr` sees them", "CLI now rasterizes supported PDFs internally"),
    (r"There is no current `pull`", "pull is now implemented"),
    (r"recognize_dynamic.*not current APIs", "dynamic-image APIs are now current"),
    (r"Current CLI reality: `convert` is scaffolded", "int8 convert is now implemented"),
    (r"focr pull installs\s+`unlimited-ocr\.focrq`", "pull installs unlimited-ocr.int8.focrq"),
    (r"structured JSON[^\n]*markdown only", "structured JSON now includes layout boxes"),
    (
        r"downloads the matching\s+binary from the `v0\.2\.0` release",
        "installer resolves latest release and current fallback is v0.4.0",
    ),
    (r"installer[^.\n]*(?:falls back|fallback)[^.\n]*`?v0\.2\.0`?", "current installer fallback is v0.4.0"),
    (r"Unreleased-after-`v0\.2\.0`", "the public installer fallback is v0.4.0; current source/tag may be ahead"),
    (r"Unreleased-after-`v0\.3\.0`", "f0a538b promotes this wave into the v0.4.0 source boundary"),
    (r"Current `v0\.3\.0` ships", "v0.4.0 is the older public release boundary; v0.5.0 is now a live GitHub release"),
    (r"Current `main` is bumped to `0\.4\.0`", "bf28fd7 bumps current source/tag to v0.5.0 and v0.5.0 is now released"),
    (r"source/README/installers to `0\.4\.0`", "source/package moved to v0.5.0 after bf28fd7; README/manual examples and fallback constants may still mention v0.4.0"),
    (r"GitHub Actions are unhealthy", "bd-4yks is closed after the CI/gate hardening wave; name remaining caveats precisely"),
    (r"GitHub Actions is unhealthy", "bd-4yks is closed after the CI/gate hardening wave; name remaining caveats precisely"),
    (r"release/download/v0\.3\.0", "manual release examples should target the current live release"),
    (r"v0\.5\.0[^.\n]*(?:release not found|without a GitHub release object)", "v0.5.0 is now a live GitHub release"),
    (r"GitHub release object/assets[^.\n]*(?:remain|still)[^.\n]*`?v0\.4\.0`?", "v0.5.0 release assets are live; only README/manual examples and fallback constants may lag at v0.4.0"),
    (r"v0\.5\.0[^.\n]*(?:reported|reports)[^.\n]*release not found", "v0.5.0 is now a live GitHub release"),
    (r"bd-4yks[^.\n]*(?:open|in progress|in-progress|not closed|pending|still routes|still belongs)", "bd-4yks is closed; keep only specific remaining caveats"),
    (r"(?:Deep fuzz|deep fuzz)\s*/\s*scheduled CI[^.\n]*(?:open|bd-4yks|still|belongs|routes)", "bd-4yks is closed; distinguish exhaustive fuzz/full-model caveats from closed CI gate evidence"),
    (r"windows-msvc-aarch64[^.\n]*(?:remaining|still|failure|red)", "advisory matrix was noted 6/6 after the SMMLA layout fix; native Windows x86_64 is supported and ARM64 Windows remains bd-3u97"),
    (r"`-o/--output`[^.\n]*Unreleased", "-o/--output shipped in v0.3.0"),
    (r"`focr models`[^.\n]*(?:tracker-planned|not current CLI)", "focr models discovery is now current"),
    (r"Model Zoo / `focr models` is tracker-planned", "focr models discovery is now current"),
    (r"planned `focr models` discovery", "focr models discovery is now current"),
    (r"(?m)^\s*focr\s+pull[^\n]*(?:--model-id|--model)\b", "pull takes an optional positional model id"),
    (r"SmolVLM2[^.\n]*(?:not|isn't|is not)[^.\n]*(?:pullable|manifest|packaged)", "SmolVLM2 is manifest-pullable after bd-av64.7; use stale-binary wording if needed"),
    (r"SmolVLM2[^.\n]*OneChart[^.\n]*TrOMR[^.\n]*not yet in `models/manifest\.json`", "SmolVLM2, OneChart, and TrOMR have current manifest pull entries after bd-av64.7"),
    (r"focr pull smolvlm2[^.\n]*(?:not current|unsupported|unavailable|does not|can't|cannot)", "focr pull smolvlm2 is current after bd-av64.7; stale binaries must be labeled stale"),
    (r"FOCR_MANIFEST_URL[^.\n]*(?:makes|enables|allows)[^.\n]*(?:smolvlm2|onechart)[^.\n]*(?:pull|download)", "manifest overrides only work when the resolved manifest actually lists the model"),
    (r"--manifest[^.\n]*(?:makes|enables|allows)[^.\n]*(?:smolvlm2|onechart)[^.\n]*(?:pull|download)", "manifest overrides only work when the resolved manifest actually lists the model"),
    (r"focr models[^.\n]*(?:proves|means|guarantees)[^.\n]*(?:focr pull|manifest|download)", "model registry readiness is separate from manifest-packaged distribution"),
    (r"multi-model pull[^.\n]*(?:not current|no current|not supported)", "focr pull got-ocr2 is now current"),
    (r"only row with `implemented=true`", "got-ocr2 is also implemented in current source"),
    (r"`unlimited-ocr` is the only ready", "got-ocr2 is also ready in current source"),
    (r"GOT-OCR2[^.\n]*(?:developer-gated|planned row|reports it as planned)", "GOT-OCR2 is ready/pullable in current source"),
    (r"source-wired", "GOT-OCR2 is ready/pullable; use implemented/ready or historical wording"),
    (r"FOCR_GOT_INT8_LMHEAD[^.\n]*(?:default-off|default off)", "GOT and SmolVLM2 lm_head int8+refine are default-on after bd-2dlz/4291807 proof"),
    (r"FOCR_BATCH_SPINE[^.\n]*presence-(?:armed|parsed)", "FOCR_BATCH_SPINE is value-parsed; =0/off/false/no disable"),
    (r"`FOCR_BATCH_SPINE=0`\s+(?:arms|enables|is armed|is enabled)", "FOCR_BATCH_SPINE=0 disables the spine"),
    (r"FOCR_QKV_FUSED[^.\n]*(?:is|remains)\s+(?:opt-in|default-off|default off|disabled by default)", "FOCR_QKV_FUSED is default-on after bd-241s; =0/off/false/no disables"),
    (r"FOCR_QKV_FUSED=1[^.\n]*(?:enables|arms|turns on|activates)", "FOCR_QKV_FUSED no longer requires =1; default is enabled"),
    (r"bd-241s[^.\n]*(?:open|in progress|in-progress|not closed|pending)", "bd-241s is closed after 98cc790/5474ae0"),
    (r"bd-wp8\.2\.2[^.\n]*(?:requires|needs|must|should)[^.\n]*(?:schema[- ]?v2|schema bump|version bump)", "staff is additive schema-v1; bd-wp8.2.2/source drift must not become a schema-v2 requirement"),
    (r"bd-wp8\.2\.2[^.\n]*(?:closed-current|is closed|status closed)", "bd-wp8.2.2 may lag open even after schema fixture/source fixes; require focused source/test/Beads check before closure claims"),
    (r"FOCR_SPEC_DECODE[^.\n]*(?:proves|certifies)[^.\n]*engagement", "spec gate currently proves output identity, not per-run engagement"),
    (r"present-but-broken[^.\n]*(?:xfail|skip|green)", "present-but-broken parity artifacts must fail loudly"),
    (r"max_concurrent_forwards\s*<=\s*1", "spine watchdog asserts max_concurrent_forwards == 1 on real pages"),
    (r"dirty/current decoder work adds `FOCR_GOT_INT8_LMHEAD`", "GOT lm_head int8 is committed current source"),
    (r"Follow-on dirty/source work may add `FOCR_GOT_INT8_LMHEAD`", "bd-2dlz follow-on is committed"),
    (r"GOT-specific lm_head int8; numerics-changing kill-switch, not a default", "GOT and SmolVLM2 lm_head int8+refine are default-on with f32 fallback"),
    (r"SmolVLM2[^.\n]*(?:f32-only pending cert|f32 only pending cert|untied.*pending cert)", "4291807 certifies the SmolVLM2 untied lm_head int8+refine runtime path"),
    (r"FOCR_MODEL_QUANT", "runtime quant preference env is FOCR_QUANT"),
    (r"no task/format CLI flag exists", "GOT --format is now current"),
    (r"no stable[^.\n]*--format", "GOT --format is now current"),
    (r"formatted-source-only", "GOT --format is now current"),
    (r"formatted-GOT CLI flag", "GOT --format is now current"),
    (r"`--task`[^.\n]*(?:not current|no current|absent)", "focr ocr --task is now current"),
    (r"task-specific Model Zoo commands \(`focr music`, `focr chart`, `--task`\) are\s+not current", "--task is current; only task subcommands are absent"),
    (r"`bd-ff4i` tracks GOT repetition", "bd-ff4i is closed and the GOT guard is implemented"),
    (r"`bd-3kix` tracks the missing specialized corpus", "bd-3kix phase 1 corpus/smokes are done"),
    (r"current CLI still has no stable `--task`", "focr ocr --task is current"),
    (r"current CLI still has no .*--task", "focr ocr --task is current"),
    (r"gundam[^.\n]*default", "default crop mode is base"),
    (r"Gundam e2e certification is still pending", "bd-1e9n now has first Gundam e2e evidence"),
    (r"Gundam e2e has no oracle cert yet", "bd-1e9n now has first Gundam e2e evidence"),
    (r"preprocess[^.\n]*(?:still-unwired|parsed but never consumed|dead surface)", "bd-1e9n wired preprocess flags"),
    (r"SmolVLM2[^.\n]*planned descriptors? only", "SmolVLM2 conversion is now implemented/proven"),
    (r"SmolVLM2[^.\n]*conversion-only", "SmolVLM2 now has C5 decoder seam evidence too"),
    (r"bd-3jo6\.3\.6[^.\n]*(?:open|pending|planned)", "bd-3jo6.3.6 tokenizer conformance is closed"),
    (r"SmolVLM2[^.\n]*tokenizer[^.\n]*(?:pending|unimplemented|not current)", "SmolVLM2 C6 tokenizer conformance is current"),
    (r"SmolVLM2[^.\n]*(?:vision|SigLIP|pixel-shuffle|connector)[^.\n]*(?:alone|by itself)[^.\n]*(?:certifies|proves)[^.\n]*(?:quality|perf)", "SmolVLM2 vision seams alone do not prove quality/perf"),
    (r"SmolVLM2[^.\n]*(?:registry row|model_arch)[^.\n]*(?:still has|marks)[^.\n]*implemented(?:=|: )false", "current source marks SmolVLM2 implemented=true"),
    (r"describe/VQA inference remains planned", "describe/VQA now has current routing; attach DISC-003/C8/C10 caveats instead"),
    (r"does not make `--task describe` runnable", "current source routes --task describe with smolvlm2; attach DISC-003/C8/C10 caveats"),
    (r"Treat SmolVLM2 as conversion-proven but inference-planned", "use conversion-proven/current-routed/C8-C10-caveated wording"),
    (r"Do not route `--task describe`", "current describe route exists; attach DISC-003/C8/C10 caveats instead"),
    (r"planned `describe`", "--task describe is current when paired with smolvlm2"),
    (r"`describe` returns a clean\s+`NotImplemented`", "--task describe now routes with smolvlm2; old NotImplemented is release lag"),
    (r"bd-3jo6\.3\.3[^.\n]*(?:open|in progress|in-progress|not closed)", "C3 SigLIP is now closed; stale open/in-progress wording"),
    (r"bd-3jo6\.3\.4[^.\n]*(?:open|in progress|in-progress|not closed)", "C4 connector is now closed; stale open/in-progress wording"),
    (r"bd-3jo6\.1\.[89][^.\n]*(?:open|in progress|in-progress|not closed)", "A8/A9 are now closed; stale open/in-progress wording"),
    (r"bd-3jo6\.3\.7[^.\n]*(?:in progress|in-progress|active)", "C7 prompt/IO-preprocess is closed in current source"),
    (r"bd-3jo6\.3\.9[^.\n]*(?:open|in progress|in-progress|not closed)", "C9 describe route is closed in current source"),
    (r"FOCR_RESAMPLE[^.\n]*selects SmolVLM2", "SmolVLM2 preprocessing uses fixed LANCZOS, not FOCR_RESAMPLE"),
    (r"SmolVLM2[^.\n]*(?:uses|default)[^.\n]*(?:BICUBIC|CatmullRom)", "SmolVLM2 C7 preprocessing uses LANCZOS, not BICUBIC/CatmullRom"),
    (r"C7[^.\n]*(?:alone|by itself)[^.\n]*(?:quality|perf|L5)", "C7 is preprocess/prompt-IO; C8/C10 gate broader quality/perf/logging"),
    (r"seam-in-progress", "SmolVLM2 C3/C4/A8/A9 are now seam-certified; use historical wording if discussing an old snapshot"),
    (r"dirty/current source", "use neutral live-checkout wording instead of dirty/current source"),
    (r"describe/VQA-not-shipped", "SmolVLM2 describe/VQA route is implemented; caveat quality/perf instead"),
    (r"source-current but C8-not-certified", "use implemented route plus DISC-003/C8/C10 scoped evidence wording"),
    (r"C8 greedy describe text is only an anchor until the full image forward/e2e gate closes", "DISC-003 is now the C8 L4 near-tie ledger"),
    (r"model_required:\s*<[^>\n]*smolvlm2-planned", "SmolVLM2 describe route is implemented; do not mark the required model as planned"),
    (r"Model Zoo work[^.\n]*SmolVLM2[^.\n]*remain planned", "SmolVLM2 describe routing is now implemented; planned wording must be historical/superseded"),
    (r"SmolVLM2,[^.\n]*remain planned", "SmolVLM2 is no longer a bare planned row in current source"),
    (r"`focr models --json` marks `unlimited-ocr` and `got-ocr2`", "SmolVLM2 is also implemented/ready in current source; add manifest-packaging caveat separately"),
    (r"Specialized tasks imply GOT\s+format mode", "only GOT structured tasks imply --format; SmolVLM2 describe must not"),
    (r"bd-3jo6\.3\.8[^.\n]*(?:open|pending|planned|not closed)", "C8 is closed in current source; keep scoped evidence wording"),
    (r"bd-3jo6\.3\.10[^.\n]*(?:open|pending|planned|not closed)", "C10 is closed in current source; keep scoped evidence wording"),
    (r"C8/C10 remain", "C8/C10 are closed in current source; use scoped evidence wording"),
    (r"C8 and C10 remain", "C8/C10 are closed in current source; use scoped evidence wording"),
    (r"C8 remains open", "C8 is closed in current source; use scoped evidence wording"),
    (r"C10 remains open", "C10 is closed in current source; use scoped evidence wording"),
    (r"C8 caveat until model-gated e2e proof exists", "C8/C10 now have scoped model-gated evidence; cite boundaries instead"),
    (r"\brun-c8-c10\b", "C8/C10 are closed; say cite-or-rerun-c8-c10 when fresh local proof is needed"),
    (r"vqa_quality_matches_oracle_l5[^.\n]*(?:public benchmark|human-label)", "VQA guard is oracle-answer evidence, not public/human-label benchmark"),
    (r"(?<!symmetric )content-word containment >= ?0\.5", "SmolVLM2 VQA guard uses symmetric content-word containment"),
    (r"smolvlm2_describe_e2e[^.\n]*(?:public benchmark|human-label)", "describe e2e is model-gated CLI proof, not a public benchmark"),
    (r"focr pull onechart[^.\n]*(?:not current|unsupported|unavailable|does not|can't|cannot|deferred|false)", "focr pull onechart is current after bd-av64.7; stale binaries must be labeled stale"),
    (r"OneChart[^.\n]*(?:not|isn't|is not)[^.\n]*(?:pullable|manifest-distributed|packaged)", "OneChart is manifest-pullable after bd-av64.7; quality and focr chart remain separate"),
    (r"checked-in manifest does not yet list a `onechart` artifact", "OneChart is now in the checked-in manifest after bd-av64.7"),
    (r"distribution through default\s+`?pull`?\s+is not a current claim", "OneChart/SmolVLM2/TrOMR default pull claims are current after bd-av64.7/.8/.9"),
    (r"bd-av64\.8[^.\n]*(?:upload gating|user-gated|still gated)", "bd-av64.8 is publication evidence; bd-av64.9 clean-cache verifies pulls"),
    (r"HF mirror[^.\n]*(?:is verified|works without auth|already green)", "HF mirror spot-checks are a known 401 gap unless live evidence supersedes this skill"),
    (r"(?:recommend|use|run|try)\s+`?focr chart\b", "OneChart CLI chart subcommand is not current; mention only as absent/deferred"),
    (r"OneChart[^.\n]*(?:still|remains|is)[^.\n]*not[^.\n]*(?:public|runtime|chart-data|OcrEngine)", "OneChart chart-data route is current with a supplied local artifact"),
    (r"OneChart[^.\n]*implemented=false", "current source marks OneChart implemented=true; implemented=false now belongs to TrOMR"),
    (r"onechart\.focrq[^.\n]*(?:preferred|runtime|chart-data)", "prefer onechart.int8.focrq for the current runtime artifact name"),
    (r"D5-D8[^.\n]*(?:remain|are still|still|remains)[^.\n]*open", "OneChart D5 native assembly is closed; cite D6/D7/D8 for remaining product gates"),
    (r"until D5-D8 close", "OneChart D5 native assembly is closed; cite D6/D7/D8 and distribution gates"),
    (r"D5 structured output[^.\n]*(?:open|remain|still open)", "OneChart D5 native assembly is closed; D6-D8 route is now closed too"),
    (r"OneChart runtime/CLI/chart-data gates remain open", "OneChart D6-D8 route gates and distribution are closed; remaining gaps are focr chart, broad quality, and JSON reliability"),
    (r"but not current runtime chart extraction", "OneChart chart-data runtime is current with a supplied local artifact"),
    (r"D3-D8[^.\n]*(?:open|pending|planned|not closed|remain)", "OneChart D3-D8 are closed in current source"),
    (r"OneChart[^.\n]*D3(?: vision)?\s*(?:is|remains|still|=|:)[^.\n]*(?:open|pending|planned|not closed)", "OneChart D3 is closed; D4-D8 are closed too"),
    (r"OneChart[^.\n]*(?:uses|requires|applies)[^.\n]*CLIP[^.\n]*(?:mean|std|constant|normaliz)", "OneChart preprocess is raw [0,1], not CLIP-normalized"),
    (r"D4-looking code", "OneChart D4 prefill half 1 is committed; use current D4-prefill wording"),
    (r"modified-live-checkout[^.\n]*D4 prefill", "OneChart D4 prefill half 1 is committed; use current D4-prefill wording"),
    (r"DecoderConfig::onechart[^.\n]*D4\s+WIP", "OneChart D4-prefill is committed; use current D4-prefill/D4 cached-decode wording"),
    (r"d4_prefill:\s*absent\|modified-live-checkout", "OP-OC exit artifact must use current D4-prefill states"),
    (r"runtime_status:\s*conversion-tokenizer-vision-only\|d4-wip", "OP-OC runtime status must include the committed D4-prefill state"),
    (r"runtime_status:\s*conversion-tokenizer-vision-prefill-only", "OP-OC runtime status must include committed D4 cached decode"),
    (r"bd-3jo6\.4\.4[^.\n]*(?:in_progress|in progress|not closed)", "bd-3jo6.4.4 is closed as of 2769d21"),
    (r"D4-prefill[^.\n]*(?:is|makes|enables|supports|provides)[^.\n]*(?:runnable|ready|implemented)[^.\n]*(?:chart-data|chart data|JSON/CSV)", "D4-prefill does not make OneChart chart-data extraction runnable"),
    (r"D4 cached decode[^.\n]*(?:is|makes|enables|supports|provides)[^.\n]*(?:runnable|ready|implemented)[^.\n]*(?:chart-data|chart data|JSON/CSV)", "D4 cached decode does not make OneChart chart-data extraction runnable"),
    (r"D4(?: cached decode| prefill)?\s+(?:is still|remains|is|:)[^.\n]{0,60}(?:in_progress|in progress|open)", "OneChart D4 is closed; D5-D8 are closed too"),
    (r"remaining D4 half is the OPT KV-cache decode/generate path", "D4 cached decode support is closed as of 2769d21"),
    (r"dirty/live D4-rest", "D4 cached decode support is closed; onechart.int8.focrq preference is committed in 2769d21"),
    (r"generate_greedy_kvcache[^.\n]*D4-rest WIP", "generate_greedy_kvcache OPT support is committed; do not call it D4-rest WIP"),
    (r"dirty/live[^.\n]*onechart\.int8\.focrq", "onechart.int8.focrq same-quantization preference is committed in 2769d21"),
    (r"onechart\.int8\.focrq[^.\n]*(?:not committed truth|unless `git log`|dirty)", "onechart.int8.focrq same-quantization preference is committed in 2769d21"),
    (r"(?:12-character|decoded-text prefix match|oracle `chat\(\)` text prefix)", "D4 close uses dict-open structural anchor, not oracle text-prefix exactness"),
    (r"opt_kvcache_matches_greedy_and_oracle[^.\n]*(?:makes|enables|supports)[^.\n]*(?:chart-data|chart data|JSON/CSV)", "D4 cached decode proof does not make chart-data product support"),
    (
        r"OneChart[^.\n]*(?:uses|routes through|requires|is)[^.\n]*Qwen",
        "OneChart tokenizer/decoder is OPT GPT-2, not Qwen; historical correction must be explicit",
    ),
    (r"`FOCR_SPEC_DECODE`[^.\n]*(?:unproven|no e2e)", "bd-1azu.36 now has ON==OFF e2e evidence"),
    (r"gauntlet[^.\n]*no current HF baseline", "bd-re8.17 now has a pinned HF runbook"),
    (r"bd-re8\\.17[^.\n]*(?:in progress|remains in progress)", "bd-re8.17 is now closed with first PERF_LEDGER rows"),
    (r"every stage wins|beats[^.\n]*every stage", "PERF_LEDGER page_0009 preprocess ratio 0.916; cite per-stage rows exactly"),
    (r"\\[SmolVLM2 Conversion\\]\\(#smolvlm2-conversion\\)", "TROUBLESHOOTING TOC must match the renamed decoder-seam section"),
    (r"\\[SC: SmolVLM2 Conversion Census\\]\\(#sc-smolvlm2-conversion-census\\)", "OPERATORS TOC must match the renamed decoder-seam operator"),
    (r"(?m)^\s*focr ocr\s+[^\n]*--f32", "only ocr-batch exposes --f32"),
    (r"focr pull tromr[^.\n]*(?:not current|unsupported|unavailable|does not|can't|cannot|deferred|false|expected)", "focr pull tromr is current; stale binaries must be labeled stale"),
    (r"TrOMR[^.\n]*(?:not|isn't|is not)[^.\n]*(?:pullable|manifest-distributed|packaged)", "TrOMR is manifest-pullable; default quant is storage-int8 after bd-av64.12"),
    (r"TrOMR[^.\n]*manifest distribution[^.\n]*(?:remain|remains)[^.\n]*(?:follow-up|separate|open)", "TrOMR distribution is current; remaining gaps are decoder-kernel/perf/dewarp/kern"),
    (r"(?mi)^(?!.*(?:--quant f32|reference|historical|older|old|pre-|before|stale|do not|not |never|claiming|treat|anti-pattern)).*focr pull tromr[^\n]*(?:installs|downloads|selects|pulls)[^\n]*(?:published )?`?f32`?[^\n]*(?:artifact|quant)", "default focr pull tromr installs tromr.int8.focrq; f32 is explicit reference mode"),
    (r"(?mi)^(?!.*(?:storage|dequant|f32 access|no .*int8 compute|not .*int8 compute|not.*perf|do not|never|anti-pattern|storage-int8|remaining|remain|outside|separate|absent|ahead|gated)).*TrOMR[^\n]*(?:int8)[^\n]*(?:compute|kernel|speed win|perf win|throughput win)", "TrOMR storage artifact does not prove decoder-kernel/perf claims"),
    (r"TrOMR[^.\n]*(?:still|remains|is)\s+(?:not runtime-ready|runtime-gated|infrastructure-only|not runnable)", "TrOMR E9 local runtime is current; keep E5/E8/E10/manifest caveats explicit"),
    (r"`tromr`[^.\n]*(?:implemented=false|marks `tromr` `implemented=false`)", "current source marks TrOMR implemented=true"),
    (r"current `--task music`[^.\n]*(?:GOT format-mode|not TrOMR)", "`--task music` is dual-lane: TrOMR with tromr.int8.focrq by default or tromr.focrq for f32 reference mode, GOT with got-ocr2"),
    (r"TrOMR music is `focr ocr --task music --model tromr\.focrq`", "TrOMR default pull uses tromr.int8.focrq; tromr.focrq is the f32 reference path after --quant f32"),
    (r"TrOMR-backed `--task music` route yet", "TrOMR E9 route exists"),
    (r"E7 assembly[^.\n]*(?:in progress|gate|gated)", "TrOMR E7 is closed; remaining gates are decoder-kernel/perf/dewarp/kern"),
    (r"E9[^.\n]*(?:remain|still|ahead|gate|gated)", "TrOMR E9 is closed; remaining gates are decoder-kernel/perf/dewarp/kern"),
    (r"E4 live WIP|E4 WIP|decoder-WIP", "TrOMR E4 is committed; E7/E9 local runtime is current"),
    (r"no E5 full-page staff detector", "fc9d88a adds the E5 v1 staff_detect module and 752f3cd closes full-page wiring"),
    (r"E5 staff detection remains open", "bd-3jo6.5.5 is closed as of 752f3cd"),
    (r"bd-3jo6\.5\.5[^.\n]*(?:in progress|open|remains open|still reports)", "bd-3jo6.5.5 is closed as of 752f3cd"),
    (r"dirty/live[^.\n]*(?:recognize_page|staves_to_musicxml|full-page)", "recognize_page/staves_to_musicxml full-page wiring is committed in 752f3cd"),
    (r"local HEAD[^.\n]*E5 v1", "E5 v1 detector is committed; avoid local-HEAD wording"),
    (r"full-page staff detection until E5", "E5 full-page staff detection is closed as of 752f3cd"),
    (r"E10 consolidated sweeps?[^.\n]*(?:remain|open|ahead)", "E10 is closed as of ab0bae0"),
    (r"bd-3jo6\.5\.10[^.\n]*(?:open|remain open|remains open|ahead|not closed)", "bd-3jo6.5.10 is closed as of ab0bae0"),
    (r"bd-3jo6\.5[^.\n]*(?:remains open|remain open)", "TrOMR sub-epic bd-3jo6.5 is closed as of ab0bae0"),
    (r"tromr\.focrq[^.\n]*single-staff `--task music`", "TrOMR E5 full-page v1 support is closed; do not describe tromr.focrq as single-staff only"),
    (r"E8 broad parity/perf", "bd-3jo6.5.8 is closed for the single-staff ladder; bd-2sez is a closed f32 baseline loss row, not broad perf proof"),
    (r"no public TrOMR (?:A11/)?PERF_LEDGER row", "bd-2sez/5430e2c adds a public f32 TrOMR PERF_LEDGER baseline row"),
    (r"public TrOMR (?:A11/)?PERF_LEDGER row until `bd-2sez`", "bd-2sez is closed; cite the f32 losing baseline row"),
    (r"public TrOMR perf row[^.\n]*(?:remain|remains|ahead|future|open)", "bd-2sez is closed; the remaining gap is perf win/int8 perf, not row existence"),
    (r"TrOMR (?:A11/)?perf row[^.\n]*(?:remain|remains|open|ahead|future)", "bd-2sez is closed; say f32 baseline loss row if discussing current perf evidence"),
    (r"bd-3jo6\.5\.8[^.\n]*(?:open|remain open|remains open|ahead)", "bd-3jo6.5.8 is closed; remaining gates are decoder-kernel/perf/dewarp/kern"),
    (r"E8[^.\n]*(?:remain|remains|still|ahead|gate|gated)[^.\n]*(?:open|quality|perf|SER|parity)", "E8 single-staff ladder is closed; scope remaining gates to decoder-kernel/perf/dewarp/kern"),
    (r"unimplemented `FOCR_TROMR_SAMPLE`|`FOCR_TROMR_SAMPLE`[^.\n]*unimplemented", "FOCR_TROMR_SAMPLE is implemented as deterministic seeded sampling"),
    (r"bd-av64\.2[^.\n]*(?:in progress|in-progress|open|not closed|partially current|partial/runtime|observability remains|observability half is not closed|until .*closes)", "bd-av64.2 is closed-current for both resilience and staff observability"),
    (r"staff_detection[^.\n]*(?:is current|implemented|available)", "The emitted TrOMR robot event is staff; staff_detection is stale bead wording"),
    (r"staff_result[^.\n]*(?:is current|implemented|available)", "The emitted TrOMR robot event is staff; staff_result is stale bead wording"),
    (r"(?:MusicPageMeta|take_music_page_meta|OcrModel::take_music_meta|OcrEngine::take_music_page_meta|robot::staff_event|music_meta_to_json)[^.\n]*(?:WIP|dirty|uncommitted|unfinished|follow-up|until .*closes)", "TrOMR staff observability is committed/current after bd-av64.2"),
    (r"`--json`[^.\n]*staves[^.\n]*(?:follow-up|unfinished|gated|remain|remains)", "TrOMR JSON staves array is current for music runs after bd-av64.2"),
    (r"schema (?:bump|version bump)[^.\n]*(?:required|needed|must|should|follow-up|remain|remains|until)[^.\n]*(?:staff|bd-av64\.2|TrOMR)", "TrOMR staff event is additive schema-v1; do not require a schema bump"),
    (r"bd-av64\.14[^.\n]*(?:broad note-level SER|full note-level SER|camera dewarp|barline splitting|TrOMR int8|perf win|performance win)", "bd-av64.14 is only scoped fit-first geometry/p169 closure"),
    (r"bd-av64\.14[^.\n]*(?:all[- ]green|unconstrained|universal)[^.\n]*(?:quality|SER|geometry|OMR)", "bd-av64.14 closure must stay scoped"),
    (r"(?:ink-extent|band-growth|extend-to-fit|neighbor-bounded)[^.\n]*(?:proves|certifies|guarantees)[^.\n]*(?:broad note-level SER|camera dewarp|barline splitting|TrOMR int8|perf)", "Committed crop-shaping mechanics do not prove adjacent TrOMR follow-ups"),
    (r"music_warning[^.\n]*(?:requires|needs|must|should)[^.\n]*(?:schema[- ]?v2|schema bump|version bump)", "music_warning is additive schema-v1 after bd-av64.5"),
    (r"music_warning[^.\n]*(?:missing from|not in|omitted from)[^.\n]*(?:robot_schema_v1|frozen schema|advertised-events|event inventory)", "music_warning is advertised in frozen schema-v1 after 0b74af0; label stale binaries/fixtures instead"),
    (r"bd-av64\.5[^.\n]*(?:auto-correct|autocorrect|fixes|repairs)[^.\n]*(?:music|MusicXML|recognition|output)", "bd-av64.5 is annotate-only telemetry, not auto-correction"),
    (r"bd-av64\.13[^.\n]*(?:still in progress|remains in progress|is in progress|open|not closed)", "bd-av64.13 is closed after 69039c3 with negative/reverted follow-ups"),
    (r"refine_band_skew[^.\n]*(?:fixed|resolved|flipped)[^.\n]*(?:no21|double-dotted|XFAIL)", "residual-skew lever 1 did not flip the no21 double-dotted XFAIL"),
    (r"FOCR_TTA", "use FOCR_TROMR_TTA for TrOMR micro-rotation voting"),
    (r"bd-av64\.12[^.\n]*(?:still in progress|remains in progress|is in progress|open|not closed|live-WIP|dirty/live)", "bd-av64.12 is closed after efccce9 as storage-int8 publication"),
    (r"TrOMR int8 distribution artifact[^.\n]*(?:remain|remains|open|gated|pending)|int8 distribution artifact[^.\n]*(?:remain|remains|open|gated|pending)", "TrOMR storage-int8 distribution is current after bd-av64.12; remaining gaps are int8 compute/perf"),
    (r"(?mi)^(?!.*(?:storage|dequant|f32|no int8 compute|not int8 compute|not.*perf|do not|never|anti-pattern|storage-int8)).*bd-av64\.12[^\n]*(?:int8 compute|speed win|perf win|throughput win|selftest)", "bd-av64.12 is storage-int8 publication, not int8 compute/perf/selftest"),
    (r"no camera[- ]dewarp/barline split", "TrOMR now has experimental FOCR_TROMR_SPLIT=1; say camera dewarp/default barline quality instead"),
    (r"camera[- ]dewarp/barline[- ]split", "split TrOMR caveats into camera dewarp/default barline quality plus experimental FOCR_TROMR_SPLIT=1 rescue"),
    (r"barline-split chunking", "avoid stale absolute barline-split wording; FOCR_TROMR_SPLIT=1 is experimental rescue, while default/lossless quality remains gated"),
    (r"bd-av64\.4[^.\n]*(?:open|in progress|in-progress|follow-up|still|remaining)", "bd-av64.4 is closed as experimental FOCR_TROMR_SPLIT=1 rescue; keep default-quality gates separate"),
    (r"(?mi)^(?!.*(?:not |treating |experimental|rescue|off-by-default)).*FOCR_TROMR_SPLIT[^\n]*(?:default behavior|lossless quality|broad SER|quality proof|perf win|camera dewarp|int8)", "FOCR_TROMR_SPLIT=1 is experimental recognition-count rescue only"),
    (r"Source at or after `eb0c70e` trims horizontal page margins", "TrOMR crop shaping is fit-first after 40ee875; already-fitting full-width crops stay full-width"),
    (r"TrOMR crop shaping is an `eb0c70e` source-current fact", "TrOMR crop shaping now needs the 40ee875 fit-first qualifier"),
    (r"Dense-page XFAILs are the `bd-av64\.14` width-clamp class", "p055/p100 are promoted floor checks after 40ee875/91d552f; do not call them dense-page XFAILs"),
    (r"robot selftest\.models[^.\n]*(?:proves|shows|demonstrates|guarantees|certifies|means)[^.\n]*(?:quality|throughput|performance|perf win|TrOMR int8)", "robot selftest.models is per-decoder int8 parity only"),
    (r"GOT[^.\n]*(?:hydrates|hydrate)[^.\n]*(?:once per batch|per batch)[^.\n]*(?:closes|closed|complete|done|shipped)[^.\n]*(?:bd-av64\.10|A11|PERF_LEDGER)", "GOT batch hydration amortization is committed source evidence, but efd83e8 is the formal bd-av64.10 G2 closeout"),
    (r"bd-av64\.10[^.\n]*(?:in progress|in-progress|remains in progress|still pending|not closed)", "bd-av64.10 is closed as measured final state after efd83e8"),
    (r"bd-av64\.10[^.\n]*(?:meets target|hit the target|hit target|closed as a win|e2e win|end-to-end win)", "bd-av64.10 closeout improves e2e but stays below the original >=1.0x target"),
    (r"bd-2mo\.26[^.\n]*(?:remains open|is open|status open|pending|awaits retake)", "bd-2mo.26 is closed after c248e6d/c4c1684 head-to-head evidence"),
    (r"3f2f97e[^.\n]*(?:model capability|runtime model|SmolVLM2 lm_head|quality win|perf win)", "3f2f97e is gauntlet harness hardening, not a model/runtime capability claim"),
    (r"gauntlet_timing\.py[^.\n]*(?:does not yet|doesn't yet|cannot|can't)[^.\n]*(?:sam\.hydrate|SAM stage|SAM/CLIP|clip\.blocks)", "3f2f97e teaches gauntlet_timing.py the current SAM/CLIP drill-down labels"),
    (r"check_ledgers\.py[^.\n]*(?:crashes|dies|fails)[^.\n]*(?:AppleDouble|\\._\\*\\.rs)", "3f2f97e skips AppleDouble ._*.rs junk in check_ledgers.py"),
    (r"Remaining (?:hot paths|suspects)[\s\S]{0,180}CLIP tower work", "bd-av64.10 now includes committed 0298651 CLIP pass 3; mention only fresh/current CLIP hotspots if timings show them"),
    (r"10/40-page long-horizon goldens remain open", "bd-1465 is closed; state the 10-page rung and 20-page reference-collapse boundary"),
    (r"bd-1465[^.\n]*(?:remains open|remain open|is open|open under|in progress|not closed)", "bd-1465 is closed after 3201e8c/e1332a7"),
    (r"dirty pre-transposed-linear perf[^.\n]*0298651", "f65fded made the broad shared-Linear pretranspose pass committed current source"),
    (r"Linear::from_row_major[\s\S]{0,160}(?:outside|beyond) committed `?0298651`?[\s\S]{0,120}(?:live-WIP|dirty|quarantine)", "Linear::from_row_major broad pass is committed after f65fded; quarantine only newer uncommitted follow-ons"),
    (r"bd-10sb\.1[^.\n]*(?:live-WIP|dirty live-WIP|until committed|until .*closed|not closed|open)", "bd-10sb.1 is closed-current after f9f4c49/2dda846; keep only new uncommitted changes as live-WIP"),
    (r"Property/fuzz infrastructure may also be live-WIP", "bd-10sb.1 property/fuzz infrastructure is closed-current; live-WIP quarantine applies only to newer uncommitted changes"),
    (r"Dirty-worktree-only surfaces[\s\S]{0,160}bd-10sb\.1", "bd-10sb.1 property/fuzz infrastructure is closed-current, not dirty-worktree-only"),
    (r"models-tromr-v1 contains `tromr\.focrq` plus the four[\s\S]{0,160}fallback from requested int8 to selected f32", "TrOMR release prose must include the later bd-av64.12 default tromr.int8.focrq boundary"),
    (r"TrOMR default-quant fallback note", "TrOMR fallback wording must be labeled historical and superseded by bd-av64.12 default storage-int8"),
    (r"Runtime/cancellation/thread-budget work is a live-checkout lane", "bd-223.2 is closed as current runtime/cancel/thread-budget source"),
    (r"Live-checkout runtime work after `ab0bae0`", "bd-223.2 is committed at 59d376b; do not describe it as pre-close live work"),
    (r"bd-223\.2[^.\n]*(?:in progress|in-progress|still in progress|until Beads closes)", "bd-223.2 is closed; stale tracker wording"),
    (r"`runs`, `sync`, and `doctor` are scaffolded", "runs/sync and doctor are current in source; stale binaries must be labeled stale"),
    (r"`runs`, `sync`, `doctor`[^.\n]*(?:remain|are)[^.\n]*(?:gated|scaffolded|phase-gated)", "do not lump closed-current runs/sync with doctor"),
    (r"doctor[^.\n]*(?:is|remains)\s+(?:scaffolded|not implemented|NotImplemented)", "doctor is implemented current-source behavior after bd-wp8.4"),
    (r"bd-wp8\.10[^.\n]*(?:remains open|is open|status open|capstone still open|not closed)", "bd-wp8.10 is closed after c29a78b/7c7bd00 release certification, published as v0.6.0 at 29516b9"),
    (r"bd-wp8\.10[^.\n]*(?:still (?:owns|decides)|remains[^.\n]*ship gate|release-readiness all-green|release-readiness[^.\n]*remains)", "bd-wp8.10 is closed; release approval is current OP-SG evidence after c29a78b/7c7bd00/29516b9"),
    (r"release-readiness approval[^.\n]*bd-wp8\.10[^.\n]*(?:remains|still)", "bd-wp8.10 is closed; release approval is current OP-SG evidence after c29a78b/7c7bd00/29516b9"),
    (r"bd-wp8\.9[^.\n]*(?:remains open|is open|status open|bundle machinery remains open|not closed)", "bd-wp8.9 is closed after c29a78b/7c7bd00 bundle certification, published as v0.6.0 at 29516b9"),
    (r"release-readiness[^.\n]*(?:ship false|not shippable|not ship-ready)", "current release-readiness scorecard reports ship true; preserve old red state only as historical"),
    (r"latest observed (?:GitHub )?release is `?v0\.5\.2`?", "latest observed GitHub release is v0.6.0; v0.5.2 is historical"),
    (r"`v0\.5\.2` is now the latest observed real GitHub release", "latest observed real GitHub release is v0.6.0; v0.5.2 is historical"),
    (r"(?:source probe saw public `origin/main` at|public `origin/main` is|`origin/main` at) `7c7bd00`", "current public origin/main maps to 592426c / v0.6.0-4-g592426c"),
    (r"(?:source probe saw public `origin/main` at|public `origin/main` is|`origin/main` at) `5df6395`", "5df6395 is the fuzz corpus commit; current public origin/main maps to 592426c / v0.6.0-4-g592426c"),
    (r"clean source describing as `v0\.5\.2-10-g7c7bd00`", "current clean source describes as v0.6.0-4-g592426c"),
    (r"clean source describing as `v0\.6\.0-3-g5df6395`", "current clean source describes as v0.6.0-4-g592426c"),
    (r"dirty diffs after `7c7bd00`|dirty diff after `7c7bd00`|uncommitted deltas after public `7c7bd00`|after public `7c7bd00` is live-WIP", "dirty/live-WIP boundary is after current public 592426c"),
    (r"dirty diffs after `5df6395`|dirty diff after `5df6395`|uncommitted deltas after public `5df6395`|after public `5df6395` is live-WIP", "dirty/live-WIP boundary is after current public 592426c"),
    (r"native Windows (?:support )?remains `?bd-3u97`?|native Windows completion \(`?bd-3u97`?\)", "native Windows x86_64 is supported; ARM64 Windows remains bd-3u97"),
    (r"v0\.5\.0-5-g18712cc", "current July 8 public source probe: 592426c / v0.6.0-4-g592426c; dirty diffs after that are live-WIP only"),
    (r"v0\.5\.0-14-g2665750", "current July 8 public source probe: 592426c / v0.6.0-4-g592426c; dirty diffs after that are live-WIP only"),
    (r"v0\.5\.0-16-gc5e535a", "current July 8 public source probe: 592426c / v0.6.0-4-g592426c"),
    (r"v0\.5\.0-17-g8bd4037", "8bd4037 belongs to public current-main ancestry now; current public probe: 592426c"),
    (r"v0\.5\.0-19-g9bc715e", "current July 8 public source probe: 592426c after release certification commits"),
    (r"v0\.5\.0-20-g3f2878d", "current July 8 public source probe: 592426c; 3f2878d precedes it as the GOT pass-6 commit"),
    (r"local `8bd4037`|local `?8bd4037`? restores|local-current[^.\n]*8bd4037|ahead-of-origin[^.\n]*8bd4037", "8bd4037 is public current-main ancestry; only dirty diffs after 592426c are live-WIP"),
    (
        r"v0\.5\.1[^.\n]*(?:release not found|without a GitHub release object|source/tag boundary only)",
        "v0.5.1 is now a live GitHub release; keep it separate from post-tag source and installed binaries",
    ),
    (
        r"v0\.5\.0-18-gb757bc0[^.\n]*(?:contradicts|invalidates|disproves)[^.\n]*v0\.5\.1",
        "an older readiness-artifact git_describe does not contradict the live v0.5.1 release",
    ),
    (
        r"v0\.5\.1[^.\n]*(?:contradicted|invalidated|disproved)[^.\n]*v0\.5\.0-18-gb757bc0",
        "an older readiness-artifact git_describe does not contradict the live v0.5.1 release",
    ),
    (
        r"(?:FOCR_NO_MMAP|mmap_load_is_byte_identical_to_owned_read|Backing::Mapped|mmap loader)"
        r"[^.\n]*\b(?:dirty|live-WIP|candidate|until committed|not committed|keep out of user-facing release docs)\b",
        "mmap loader behavior is committed in 507cebe; only the remaining bd-2mo.22 allocator work is open",
    ),
    (
        r"bd-2mo\.22[^.\n]*(?:is closed|status closed|fully closed|complete|done)",
        "bd-2mo.22 remains open after the shipped mmap half; alignment/buffer-reuse/mimalloc remain",
    ),
    (
        r"(?:507cebe|FOCR_NO_MMAP|mmap_load_is_byte_identical_to_owned_read|Backing::Mapped)"
        r"[^.\n]*\b(?:perf win|performance win|release asset|GitHub release|installer asset)\b",
        "the mmap half is loader correctness/resident-memory evidence, not perf or release-asset proof",
    ),
    (
        r"(?:OnechartStatics|onechart\.hydrate\(cached\)|onechart_statics)"
        r"[^.\n]*\b(?:dirty|live-WIP|candidate|until committed|not committed|not current)\b",
        "OneChart statics caching is committed pass-7 source evidence after 38ab806/a9a406e",
    ),
    (
        r"(?:SmolStatics|smolvlm2\.hydrate\(cached\)|smol_statics)"
        r"[^.\n]*\b(?:dirty|live-WIP|candidate|until committed|not committed|not current)\b",
        "SmolVLM2 statics caching is committed pass-8 source evidence after 9b2a03b",
    ),
    (
        r"9b2a03b[^.\n]*(?:closes|closed|complete|done)[^.\n]*bd-av64\.10",
        "9b2a03b is SmolVLM2 pass-8 source evidence; efd83e8 is the bd-av64.10 formal closeout",
    ),
    (
        r"v0\.5\.2[^.\n]*(?:release not found|without a GitHub release object|source/tag boundary only|source-only)",
        "v0.5.2 is now a live GitHub release; keep post-release efd83e8 source separate from release assets",
    ),
    (
        r"(?:source probe saw public `origin/main` at|public `origin/main` is|`origin/main` at) `4cedacd`",
        "4cedacd marks the v0.5.2 source tag; current public origin/main: 592426c / v0.6.0-4-g592426c",
    ),
    (
        r"(?:source probe saw public `origin/main` at|public `origin/main` is|`origin/main` at) `0924479`",
        "0924479 maps to the README-only post-tag clarification; current public origin/main maps to 592426c",
    ),
    (
        r"(?:source probe saw public `origin/main` at|public `origin/main` is|`origin/main` at) `efd83e8`",
        "efd83e8 maps to the formal bd-av64.10 closeout; current public origin/main maps to 592426c",
    ),
    (r"nine commits after (?:source tag )?`v0\.5\.1`", "current public origin/main is v0.6.0-4-g592426c"),
    (r"Dirty diffs after `4cedacd`|dirty diff after `4cedacd`|uncommitted deltas after public `4cedacd`|public `4cedacd` is live-WIP", "dirty/live-WIP boundary is after current public 592426c; 4cedacd remains the v0.5.2 tag"),
    (r"through public `origin/main` `4cedacd`|extend through public `origin/main` `4cedacd`", "current public origin/main extends through 592426c"),
    (r"public `0924479`\s+is\s+live-WIP(?!; `0924479` itself is committed)", "0924479 itself maps to committed README-only clarification; current public head maps to 592426c"),
    (r"dirty diffs after `0924479`|dirty diff after `0924479`|uncommitted deltas after public `0924479`", "dirty/live-WIP boundary is after current public 592426c"),
    (r"dirty diffs after `efd83e8`|dirty diff after `efd83e8`|uncommitted deltas after public `efd83e8`", "dirty/live-WIP boundary is after current public 592426c"),
    (r"dirty diffs after `3f2f97e`|dirty diff after `3f2f97e`|uncommitted deltas after public `3f2f97e`", "dirty/live-WIP boundary is after current public 592426c"),
    (r"source is currently at `7c7bd00`|current source[^.\n]*`7c7bd00`", "current source is at 592426c / v0.6.0-4-g592426c; 7c7bd00 is the Beads closeout commit"),
    (r"v0\.5\.2-2-gefd83e8[^.\n]*(?:clean source|current source|origin/main|public source head)", "current clean source describes as v0.6.0-4-g592426c"),
    (r"v0\.5\.2-3-g3f2f97e[^.\n]*(?:clean source|current source|origin/main|public source head)", "current clean source describes as v0.6.0-4-g592426c"),
    (
        r"(?:README|source)[^.\n]*0924479[^.\n]*(?:runtime|source code|Rust source|feature)[^.\n]*(?:changed|adds|added|implements)",
        "0924479 is README-only source-vs-binary clarification, not a runtime/source feature change",
    ),
    (
        r"Hugging Face " r"mirror[^.\n]*(?:\bveri"
        r"fied\b|\bgreen\b|\bavailable\b|\bworks\b|\bserved\b|production veri"
        r"fied)|HF mirrors?\b[^.\n]*(?:\bveri"
        r"fied\b|\bgreen\b|\bavailable\b|\bworks\b|\bserved\b)",
        "Secondary weights mirror still has 401 evidence; GitHub-first pulls are the verified path",
    ),
    (
        r"(?mi)^(?!.*(?:old|older|historical|pre-`?c29a78b|debugging|superseded)).*rounds=(?:0|6|8)/10",
        "current release convergence detail is rounds=11/10, tail_clean=True; old red-state examples must be labeled historical",
    ),
    (r"--bundle[^.\n]*(?:certified false|certified:false|not certified)", "current bundle is certified:true after c29a78b"),
    (r"(?mi)^(?!.*(?:not |do not|instead|rather than|After 9bc715e|after `9bc715e`|Use OP-SG)).*certification_bundle[^.\n]*(?:hard-coded red|hardcoded red|hard-coded|hardcoded|self-referential|self referential)", "after 9bc715e certification_bundle is a live release_certificate cell; current c29a78b evidence is green"),
    (r"bd-wp8\.9[^.\n]*(?:remains open|status open|not closed)", "bd-wp8.9 is closed after c29a78b/7c7bd00"),
    (r"FOCR_SIGLIP_SEQ=1[^.\n]*(?:enables|turns on|activates|arms)[^.\n]*batch", "FOCR_SIGLIP_SEQ=1 is the kill switch back to sequential SigLIP frames"),
    (r"(?mi)^(?!.*(?:Treat|Do not|not |remain|pending|Use OP)).*frame-batched[^.\n]*SigLIP[^.\n]*(?:formal|quiet-host|PERF_LEDGER|A11)[^.\n]*(?:row|proof|win)", "frame-batched SigLIP is byte-identical source-current evidence; do not conflate it with 4291807 head certification or c248e6d head-to-head rows"),
    (r"(?mi)^(?!.*(?:Treat|Do not|not |bounded|below|without overclaiming)).*deep fuzz[^.\n]*(?:exhaustive|release-ready|ship-ready)", "round-8 deep fuzz is bounded clean evidence, not exhaustive fuzzing or release approval"),
    (r"SIMD[-/ ]?exp[^.\n]*(?:speed win|current lever|remaining hot path|landed win|kept win|enabled)", "SIMD/polynomial-exp softmax was measured dead, reverted, and ledgered as negative evidence"),
    (r"polynomial-exp softmax[^.\n]*(?:speed win|current lever|remaining hot path|landed win|kept win|enabled)", "polynomial-exp softmax was measured dead, reverted, and ledgered as negative evidence"),
    (r"row[- ]tiled SAM[^.\n]*(?:speed win|current lever|remaining hot path|landed win|kept win|enabled|easy win)", "row-tiled SAM attention was publicly restored/ledgered as negative after slower same-regime measurement"),
    (r"row[- ]tiled SAM[^.\n]*(?:local-current|local current|local negative|local baseline restore)", "row-tiled SAM negative evidence is public current-main after b757bc0"),
    (r"GotStatics[^.\n]*(?:dirty|live[- ]WIP|uncommitted|until committed|not shipped|not public-main)", "Current source includes GotStatics after 3f2878d; quarantine only newer diffs"),
    (r"got\.hydrate\(cached\)[^.\n]*(?:dirty|live[- ]WIP|uncommitted|until committed|not shipped|not public-main)", "got.hydrate(cached) is committed public current-main source after 3f2878d"),
    (r"For `tromr`, expect sole quant `f32`", "TrOMR pull now defaults to tromr.int8.focrq and keeps tromr.focrq as the f32 reference"),
    (r"distribution:\s*manifest-pull-f32\|local-artifact-only\|unknown", "TrOMR distribution artifact must distinguish default int8 and f32 reference pulls"),
    (r"(?:3\.37x|2\.58x|1\.67x)[^.\n]*(?:are|is|shows|show|prove|proves|mean|means)[^.\n]*(?:end-to-end|e2e)[^.\n]*(?:speedup|win|faster)", "A11 zoo ratios are decode-per-token rows, not end-to-end speedup claims"),
    (r"A11 zoo[^.\n]*(?:all stages|every stage)[^.\n]*(?:win|faster|speedup)", "A11 zoo rows must keep stage-specific and e2e boundaries separate"),
    (r"conformal ratchet[^.\n]*(?:is|means|proves)[^.\n]*(?:ship-ready|ship approval|release approval)", "conformal ratchet is a release-evidence instrument, not ship approval"),
    (r"Ville e-process[^.\n]*(?:is|means|proves)[^.\n]*(?:ship-ready|ship approval|release approval)", "Ville e-process monitors are release-evidence instruments, not ship approval"),
    (r"capacity certificate[^.\n]*(?:is|means|proves)[^.\n]*(?:ship-ready|ship approval|release approval)", "capacity certificate is a release-evidence instrument, not ship approval"),
    (r"bd-av64\.11[^.\n]*(?:in_progress|in progress|open|fresh audit)", "bd-av64.11 is closed after 11f60ea/9546571/5679268/b3f74b6"),
    (r"content_rotation[^.\n]*(?:experiment|live worktree|uncommitted|not committed)", "content_rotation is committed current source after 9546571"),
    (r"\| `runs` \| scaffolded \|", "CLI status table must reflect closed bd-223.4 current source vs older-binary scaffold"),
    (r"\| `sync` \| scaffolded \|", "CLI status table must reflect closed bd-223.4 current source vs older-binary scaffold"),
    (r"bd-223\.4[^.\n]*(?:still|currently)?\s*(?:in[_ -]?progress|open|until Beads closes)", "bd-223.4 is closed; only older binaries are stale/scaffolded"),
    (r"live-checkout `bd-223\.4`|`bd-223\.4` live checkout|Run-store WIP \(`bd-223\.4`\)|bd-223\.4[^.\n]*live[- ]?WIP", "bd-223.4 is committed/closed current source, not live-checkout WIP"),
    (r"bd-zc1o[^.\n]*(?:open|pending|planned|not closed)", "bd-zc1o robot schema contract is closed in current source"),
    (r"bd-n68o[^.\n]*(?:open|pending|planned|not closed)", "bd-n68o structured test logging is closed in current source"),
    (r"bd-29wv[^.\n]*(?:open|pending|planned|not closed)", "bd-29wv model-gated e2e runner is closed in current source"),
    (r"bd-re8\.7[^.\n]*(?:open|pending|planned|not closed)", "bd-re8.7 L5 OCR parity gate is closed in current source"),
    (r"bd-3kge[^.\n]*(?:open|pending|planned|not closed)", "bd-3kge shared determinism gate is closed in current source"),
    (r"bd-2pgf[^.\n]*(?:open|pending|planned|not closed)", "bd-2pgf fixture provenance/manifest is closed in current source"),
    (r"no shared determinism gate", "bd-3kge adds shared assert_deterministic helpers"),
    (r"fixture manifest[^.\n]*(?:missing|absent)", "bd-2pgf adds tests/fixtures/MANIFEST.toml"),
    (r"bd-re8\.12[^.\n]*(?:open|pending|planned|not closed)", "bd-re8.12 conformance matrix is closed in current source"),
    (r"no conformance matrix", "bd-re8.12 adds tests/conformance_matrix.rs"),
    (r"ConformanceTest[^.\n]*(?:missing|absent|not implemented)", "bd-re8.12 adds ConformanceTest"),
    (r"MUST coverage[^.\n]*(?:missing|absent|not gated)", "bd-re8.12 gates MUST coverage >= 0.95"),
    (r"bd-re8\.9[^.\n]*(?:open|pending|planned|not closed)", "bd-re8.9 differential suite is closed in current source"),
    (r"bd-re8\.10[^.\n]*(?:open|pending|planned|not closed)", "bd-re8.10 metamorphic suite is closed in current source"),
    (r"bd-re8\.11[^.\n]*(?:open|pending|planned|not closed)", "bd-re8.11 golden suite is closed in current source"),
    (r"bd-re8\.19[^.\n]*(?:open|pending|planned|not closed|still reported|still reports)", "bd-re8.19 is closed-current after 1b84428/1112cf8 close evidence"),
    (r"source-present runner[^.\n]*bd-re8\.19[^.\n]*(?:open|tracker)", "bd-re8.19 is now tracker-closed; keep only run-level skip/all_green caveats"),
    (r"bd-re8\.19[^.\n]*source-present ladder scorecard runner[^.\n]*not[^.\n]*closed", "bd-re8.19 is closed-current after 1b84428/1112cf8 close evidence"),
    (r"no differential suite", "bd-re8.9 adds the oracle differential comparator"),
    (r"no metamorphic suite", "bd-re8.10 adds tests/metamorphic.rs"),
    (r"no golden suite", "bd-re8.11 adds tests/cli_robot_golden.rs"),
    (r"CI[^.\n]*(?:sets|exports|enables)[^.\n]*UPDATE_GOLDENS=1", "golden refresh must stay manual and forbidden in CI"),
    (r"robot selftest[^.\n]*(?:proves|shows|demonstrates)[^.\n]*(?:speed|throughput|faster|performance)", "robot selftest proves kernel parity, not performance"),
    (r"AMX where applicable", "AMX is not advertised as a current focr backend"),
    (r"artifact[- ]load tax", "bd-av64.10 supersedes artifact-load-tax wording; current GOT tax is SAM vision/attention"),
    (r"sam\.hydrate[^.\n]*(?:dominates|bottleneck|tax)", "bd-av64.10 says sam.hydrate is negligible; SAM attention/vision is the tax"),
    (r"bd-av64\.10[^.\n]*(?:first optimization evidence|pass 1 only)", "bd-av64.10 now includes f3d3215 pass-2 head-parallel global attention evidence"),
    (r"bd-3jo6\.1\.7\.5[^.\n]*(?:in progress|in-progress|remains open|still in progress|not closed|until Beads closes|until the bead closes)", "bd-3jo6.1.7.5 dense batched decode is closed/current after fdd1d64"),
    (r"(?:dirty|live[- ]worktree|live checkout)[^.\n]*(?:recognize_batch_dense|smolvlm2::recognize_batch|onechart::recognize_batch|FOCR_BATCH_PACK|DEFAULT_BATCH_SIZE|MAX_BATCH_SIZE)", "dense zoo batching is committed/current after 4ca1577/fdd1d64, not dirty WIP"),
    (r"SmolVLM2/OneChart[^.\n]*(?:not|isn't|is not|no)[^.\n]*(?:route|routing|batched|dense)", "SmolVLM2 and OneChart dense batching are current after 4ca1577/fdd1d64"),
    (r"generate_greedy_batched[^.\n]*(?:proves|means|guarantees)[^.\n]*(?:fairness|PERF_LEDGER|batched lm_head|B>=8)[^.\n]*(?:throughput|speedup|ocr-batch)", "dense batch closure is lossless/scoped, not broad fairness/lm_head/B>=8 throughput proof"),
    (r"FOCR_BATCH_SIZE[^.\n]*(?:default|defaults)[^.\n]*(?:to )?(?<!\d)8(?!\d)", "current shared batch scheduler default: 128/cap 256; cite decoder.rs explicitly for the historical internal helper"),
    (r"FOCR_BATCH_PACK[^.\n]*(?:changes|alters|modifies)[^.\n]*(?:tokens|token stream|markdown|text|semantics)", "FOCR_BATCH_PACK is admission ordering only and must restore byte-identical output"),
    (r"GOT(?:-OCR2)?[^.\n]*FOCR_BATCH_SPINE[^.\n]*(?:falls back|sequential arch-dispatched path)", "after cf0b037, GOT has a dense spine route under FOCR_BATCH_SPINE"),
    (r"bd-av64\.6[^.\n]*(?:broad note-level SER|full note-level SER|complete note-level SER|10-20 item expansion complete|GOT cross-reference complete|aggregate SER complete)", "bd-av64.6 is only scoped corpus-v1 measurement closure"),
    (r"real-scan[^.\n]*(?:broad note-level SER complete|full note-level SER|complete note-level SER)", "real-scan corpus v1 is not broad note-level SER completion"),
    (r"(?mi)^(?!.*(?:do not|not a valid|false relation|invalid|guard|assert|reject)).*multi-page[^\n]*(?:equals|must equal|same as)[^\n]*(?:concatenated|summed|single-page)", "multi-page parsing is cross-page dependent, not concat/sum of single-page outputs"),
    (r"Base-640", "multi-page source-current preprocessing uses 640x640 preprocess_dynamic_squash, not aspect-preserving Base padding"),
    (r"bd-2z0y[^.\n]*(?:remains open|still open|open for streaming|streaming half remains|streaming half open)", "bd-2z0y is closed for PDF multi-page plus streaming decoded page progress events"),
    (r"streaming[^.\n]*page[^.\n]*events[^.\n]*(?:remain open|still open|not current|do not promise those events)", "streaming decoded page progress events are current; only layout/figure/split semantics remain absent"),
    (r"(?mi)^(?!.*(?:do not|does not|not |but not|refuses|unsupported|invalid|current output is|remains open)).*--multi-page[^\n]*(?:supports|provides|includes|emits|returns|works with|composes with)[^\n]*(?:per-page layout|layout boxes|extract-figures|split-spreads)", "current multi-page route does not provide layout boxes, figure extraction, or split-spread composition"),
    (r"(?mi)^(?!.*(?:do not|not |treat|tag-only|layout/correctness|rather than)).*aarch64-smmla[^\n]*(?:speed win|performance win|faster|throughput)", "offline SMMLA prepacking is layout/correctness evidence, not speed evidence"),
    (r"(?mi)^(?!.*(?:tag-only|do not|not |until|remain|remains|absent)).*(?:x86-vnni|x86-amx|VNNI|AMX)[^\n]*(?:packed-consuming|packed consuming|consumes packed|zero-shuffle)[^\n]*(?:kernel|kernels|path)", "VNNI/AMX arch tags are tag-only until packed-consuming x86 kernels land"),
    (r"goldens/\*\.musicxml[^.\n]*(?:are|as)\s+(?:the\s+)?(?:human truth|ground truth|tier 1 truth)", "real-scan MusicXML goldens are frozen model-output anchors, not human truth"),
    (r"FOCR_FUSE_NGRAM_LMHEAD[^.\n]*(?:default-on|default on|speed win|is a win|pays)", "bd-2mo.24 says ngram-lmhead fusion is correct but does not pay"),
    (r"bench_guardrail\.py[^.\n]*(?:proves focr faster|speed proof|head-to-head proof)", "bench_guardrail.py is a regression guardrail, not a speed proof"),
    (r"`--ratchet`[^.\n]*(?:runs in CI|run in CI|automatic baseline|auto-ratchet|automatically updates)", "bench baselines move only by explicit reviewed ratchet, never automatically in CI"),
    (r"Phase[- ]3[^.\n]*(?:complete|done|closed)", "Phase-3 parent bd-2mo remains open despite many closed kernel/proof beads"),
]

REQUIRED_TERMS = [
    "install.sh",
    "install.ps1",
    "focr --version",
    "target/release/focr",
    "cargo install --git",
    "release lag",
    "v0.4.0",
    "v0.5.0",
    "v0.5.1",
    "v0.5.2",
    "Cold-Start Boundary Card",
    "Fresh-Agent Reading Plan",
    "operator console",
    "project-local skill",
    "five different truth surfaces",
    "non-draft, non-prerelease",
    "8de3674",
    "507cebe",
    "0401df2",
    "a391793",
    "c8682a3",
    "38ab806",
    "a9a406e",
    "9b2a03b",
    "8d6601d",
    "4cedacd",
    "0924479",
    "efd83e8",
    "3f2f97e",
    "4291807",
    "91c12fd",
    "ae7b8f2",
    "c248e6d",
    "c4c1684",
    "c29a78b",
    "7c7bd00",
    "29516b9",
    "beaed7c",
    "db02421",
    "5df6395",
    "592426c",
    "v0.5.2-3-g3f2f97e",
    "v0.5.2-10-g7c7bd00",
    "v0.6.0-3-g5df6395",
    "v0.6.0-4-g592426c",
    "v0.5.2 — the cold-start release",
    "published 2026-07-08T06:05:23Z",
    "v0.6.0 — certified faster than PyTorch, end to end",
    "published 2026-07-08T14:47:48Z",
    "bd-av64.10-g2r",
    "bd-2mo.26",
    "AppleDouble",
    "OUT_DIR",
    "page_0009 e2e",
    "page_0014 e2e",
    "3.41x",
    "2.81x",
    "1.85x",
    "1.92x",
    "FOCR_GOT_INT8_LMHEAD=0",
    "int8+refine",
    "0.624 -> 0.885",
    "0.546 -> 0.755",
    "0.878 -> 0.890",
    "3.046x",
    "2.249x",
    "1.499x",
    "v0.5.0-18-gb757bc0",
    "post-tag",
    "f0a538b",
    "bf28fd7",
    "e80360b",
    "cc79d70",
    "c960b77",
    "29aa40a",
    "7777e34",
    "2e5801b",
    "18712cc",
    "ab6e083",
    "50d5dad",
    "ab6fa6c",
    "3f3d9d0",
    "8cacf52",
    "ff22366",
    "f1ac972",
    "2665750",
    "48a9896",
    "c5e535a",
    "8bd4037",
    "b757bc0",
    "9bc715e",
    "3f2878d",
    "bd-4yks",
    "gate-log",
    "bench-guardrail",
    "4.7M",
    "3.65M",
    "3,271",
    "PROPTEST_CASES=2048",
    "TEST_LOG_DIR",
    "bd-3u97",
    "ARM64 Windows",
    "native Windows x86_64",
    "check_release_linkage",
    "4ca1577",
    "fdd1d64",
    "53f6581",
    "focr pull",
    "focr pull --manifest",
    "focr pull got-ocr2",
    "focr pull smolvlm2",
    "focr pull onechart",
    "focr pull tromr",
    "unlimited-ocr.int8.focrq",
    "got-ocr2.int8.focrq",
    "models/manifest.json",
    "BUILTIN_MANIFEST_JSON",
    "ModelEntry.sidecars",
    "select_quant",
    "pull.in_manifest",
    "pull.quants",
    "bd-av64.7",
    "bd-av64.8",
    "bd-av64.9",
    "bd-av64.10",
    "0298651",
    "f65fded",
    "3c1b1ea",
    "bd-av64.10-simd-exp",
    "FOCR_SAM_FAST_EXP",
    "row-tiled SAM global attention",
    "bd-av64.10-rowtile",
    "untiled baseline",
    "GotStatics",
    "got.hydrate(cached)",
    "FOCR_NO_MMAP",
    "Backing::Mapped",
    "mmap_load_is_byte_identical_to_owned_read",
    "mmap half SHIPPED",
    "OnechartStatics",
    "onechart.hydrate(cached)",
    "SmolStatics",
    "smol_statics",
    "smolvlm2.hydrate(cached)",
    "Beads comment 91",
    "pass-8",
    "all four zoo lanes",
    "LinearParams::from_row_major",
    "vision_sam::Linear::from_row_major",
    "ClipWeights",
    "FOCR_SIGLIP_SEQ",
    "forward_frames_batched",
    "batched_frames_match_sequential_byte_for_byte",
    "bd-1gv.25",
    "bd-2z0y",
    "bd-1gv.26",
    "bd-1465",
    "l5_multi_page_10p_long_horizon",
    "e1332a7",
    "0.4045",
    "reference itself",
    "bd-av64.4",
    "--multi-page",
    "recognize_multi_page",
    "recognize_multi_page_dynamic",
    "recognize_multi_page_dynamic_streaming",
    "preprocess_dynamic_squash",
    "page_decoded_event",
    "batch.multi_page",
    "<PAGE>",
    'status:"decoded"',
    "a2dd1c9",
    "750a69a",
    "828ea4c",
    "727701b",
    "6e297f6",
    "c6ab897",
    "64edce3",
    "FOCR_TROMR_SPLIT",
    "barline_columns",
    "recognize_split",
    "bd-av64.6",
    "af13d3e",
    "scripts/realscan_music_gate.sh",
    "tests/fixtures/realscan_music",
    "realscan_music/v1",
    "truth/attributes.json",
    "min_recognized",
    "p055",
    "p100",
    "goldens/*.musicxml",
    "XFAIL-never-SKIP",
    "Spohr",
    "SMILES",
    "semantic",
    "bd-av64.13",
    "bd-av64.5",
    "d51d7d9",
    "39651e6",
    "sanity_warnings",
    "music_warning",
    "focr-sanity",
    "overfull_bar",
    "underfull_bar",
    "impossible_duration",
    "key_mismatch",
    "refine_band_skew",
    "FOCR_TROMR_TTA",
    "69039c3",
    "efccce9",
    "tromr.int8.focrq",
    "--quant f32",
    "no f32 quant mode",
    "storage-int8",
    "DISC-005",
    "QInt8PerChan",
    "dequant_qint8",
    "Decoder::Seq2SeqDense",
    "bd-10sb.1",
    "f9f4c49",
    "2dda846",
    "proptest",
    "PROPTEST_CASES",
    "cargo-fuzz",
    "tests/property_suite.rs",
    "tests/support/proptest_support.rs",
    "fuzz/",
    "focrq_parse",
    "safetensors_parse",
    "image_decode",
    "pretok_split",
    "decompression_bomb_png_is_rejected_before_allocation",
    "bd-1a6h",
    "60d8af4",
    "scripts/bench_guardrail.py",
    "benches/.bench-history/baseline.json",
    "--ratchet",
    "cv_pct > 5",
    "noise_ineligible",
    "posture_mismatch",
    "bd-2mo.24",
    "a0ad299",
    "fused_ngram_lmhead_is_byte_identical_to_separate_mask",
    "16.43s -> 16.40s",
    "ngram_window=1024",
    "bd-1es",
    "bd-2mo.1",
    "bd-2mo.3",
    "bd-2mo.3.1",
    "bd-2mo.22",
    "fcb8289",
    "aarch64-smmla",
    "SmmlaPanels",
    "WeightLayout::SmmlaPanels",
    "src/simd/pack.rs",
    "arch_target",
    "fdbaaec",
    "9989bc0",
    "5c64547",
    "bd-241s",
    "98cc790",
    "5474ae0",
    "bd-1waa",
    "bd-3pg7",
    "qkv_fused_enabled",
    "fuse_qkv",
    "CachedLayerI8.qkv",
    "fused_qkv_gemv_is_byte_identical_to_three_calls",
    "FOCR_QKV_FUSED=0",
    "FOCR_ATTN_GEMM",
    "FOCR_INT8_KV",
    "bd-wp8.2.2",
    "adb4ee6",
    "0b74af0",
    "robot_selftest_proves_per_model_kernel_parity_e2e",
    "bd-3jo6.1.12",
    "44/44",
    "robot_schema_matches_frozen_contract_fixture",
    "robot_schema_advertises_version_and_all_events",
    "[Robot Schema Golden Drift](#robot-schema-golden-drift)",
    "[QKV Fused Decode Confusion](#qkv-fused-decode-confusion)",
    "bd-av64.2",
    "bd-av64.14",
    "3ae26b1",
    "eb0c70e",
    "40ee875",
    "91d552f",
    "fit-first",
    "ink-extent",
    "extend-to-fit",
    "neighbor-bounded",
    "fitting_bands_keep_the_classic_full_width_geometry",
    "trim_cuts_page_margins_but_keeps_ink",
    "wide_staff_with_room_fits_the_positional_budget",
    "packed_staves_stop_at_the_midline",
    "unpressured_band_keeps_the_generous_margins",
    "tromr_page_skips_overwide_staff_and_keeps_the_rest",
    "tromr_page_all_staves_failing_is_a_named_error",
    "8af3887",
    "4e881d7",
    "ece14f9",
    "models-smolvlm2-v1",
    "models-onechart-v1",
    "models-tromr-v1",
    "clean-cache",
    "idempotent repull",
    "HF mirror",
    "401",
    "FOCR_MANIFEST_URL",
    "resolve_manifest_source",
    "manifest_entry",
    "--output",
    "--extract-figures",
    "--figures-dir",
    "focr robot backends",
    "focr robot selftest",
    "recognize_dynamic",
    "recognize_with_layout",
    "recognize_dynamic_with_layout",
    "recognize_with_figures",
    "recognize_dynamic_with_figures",
    "RecognizedDocument",
    "LayoutSpan",
    "ExtractedFigure",
    "focr models",
    "focr models --json",
    "Model Zoo",
    "--model-id",
    "--arch",
    "model_id",
    "got-ocr2",
    "--format",
    "--task",
    "FOCR_GOT_FORMAT",
    "FOCR_GOT_NO_REPEAT_NGRAM",
    "FOCR_NO_REPEAT_NGRAM",
    "CONTROL_CORRECTION.md",
    "FOCR_WATCHDOG_IMAGE",
    "max_concurrent_forwards=1",
    "present-but-broken",
    "WeightsLoad",
    "FixtureParse",
    "same-page",
    "run_*.meta.json",
    "bd-2dui",
    "FOCR_MAX_NEW_TOKENS",
    "FOCR_BATCH_VISION",
    "FOCR_RESAMPLE",
    "pil-bicubic",
    "qwen.tiktoken",
    "ready/implemented",
    "format=false",
    "format=true",
    "OCR with format:",
    "Mathpix-Markdown",
    "bd-3jo6.2.10",
    "bd-3jo6.1.5",
    "bd-3jo6.1.6",
    "bd-3jo6.1.7",
    "bd-3jo6.1.7.5",
    "8497080",
    "cf0b037",
    "4ca1577",
    "fdd1d64",
    "gemm_i8_bias_prequant_batched",
    "BatchedQwen2KvCache",
    "qwen2_batched_decode_step",
    "DenseDecoderBatchStep",
    "generate_greedy_batched",
    "PageStream::with_max_emit",
    "recognize_batch_dense_got",
    "recognize_batch_dense",
    "smolvlm2::recognize_batch",
    "onechart::recognize_batch",
    "max_emit",
    "DEFAULT_BATCH_SIZE",
    "MAX_BATCH_SIZE",
    "caps: &[usize]",
    "recognize_batch_matches_sequential_e2e",
    "1.32x",
    "1.27x",
    "got::recognize_batch",
    "01f07fe",
    "f3d3215",
    "head-parallel",
    "attn(win)",
    "attn(GLOBAL)",
    "sam.forward",
    "3.4-3.6s",
    "4.6-4.8s",
    "13.5s",
    "armed GOT 8/8",
    "vision_sam",
    "clippy -D",
    "bit-identical per stream",
    "bd-ff4i",
    "bd-3kix",
    "bd-3j3p",
    "bd-30me",
    "bd-31vc",
    "bd-1e9n",
    "bd-1azu.36",
    "bd-3jo6.3.2",
    "bd-3jo6.3.5",
    "bd-3jo6.3.6",
    "bd-3jo6.3.7",
    "bd-3jo6.3.9",
    "bd-3jo6.3.3",
    "bd-3jo6.3.4",
    "bd-3jo6.3.8",
    "bd-3jo6.3.10",
    "bd-3jo6.3",
    "C10",
    "bd-3jo6.1.8",
    "bd-3jo6.1.9",
    "seam-certified",
    "NaViT bucketized",
    "4.4e-4",
    "2.59e-4",
    "1.1e-3",
    "PretokScheme",
    "SmolLm2",
    "Digits(individual_digits=true)",
    "ByteLevel(use_regex=true)",
    "FOCR_SMOLVLM2_TOKENIZER_JSON",
    "FOCR_SMOLVLM2_CORPUS",
    "FOCR_SMOLVLM2_QUESTION",
    "FOCR_SMOLVLM2_CERT_FULL",
    "--question",
    "src/native_engine/smolvlm2.rs",
    "OcrTask::Describe",
    "forward_smolvlm2",
    "set_smolvlm2_question",
    "describe_prompt_ids",
    "build_inputs_embeds",
    "DecoderConfig::smolvlm2",
    "source-current",
    "model_arch",
    "implemented=true",
    "DISC-003",
    "<5e-5",
    "64/64",
    "rank-2",
    "top-2 gap <= 0.5",
    "focr pull smolvlm2",
    "preprocess_smolvlm2",
    "preprocess_smolvlm2_path",
    "resize_lanczos",
    "LANCZOS",
    "SmolVLMImageProcessor",
    "resample: 1",
    "Pillow 12.3.0",
    "seed 301466",
    "OP-SP",
    "bd-re8.17",
    "bd-1azu.10",
    "bd-1azu.14",
    "TokenizerOps",
    "GQA",
    "SmolVLM2",
    "smolvlm2.int8.focrq",
    "vqa_quality_matches_oracle_l5",
    "scripts/gen_smolvlm2_vqa_fixtures.py",
    "scripts/smolvlm2_describe_e2e.sh",
    "smolvlm2_describe_e2e/v1",
    "tests/fixtures/smolvlm2/vqa_fixtures.json",
    "symmetric content-word containment",
    "wrong-family",
    "exit 3",
    "exit 2",
    "70%",
    "50%",
    "7/7",
    "OQ-6",
    "OP-VQ",
    "describe-vqa",
    "bd-3jo6.4.2",
    "bd-3jo6.4.3",
    "bd-3jo6.4.4",
    "bd-3jo6.4.5",
    "bd-3jo6.4.6",
    "bd-3jo6.4.7",
    "bd-3jo6.4.8",
    "bd-3jo6.4.9",
    "bd-3jo6.4",
    "bd-2lje",
    "20ac599",
    "0145419",
    "2a56c96",
    "2c77d21",
    "2769d21",
    "e926c46",
    "9cb91f9",
    "onechart",
    "OP-OC",
    "FOCR_ONECHART_DIR",
    "onechart_view_tensor",
    "vision_features",
    "model.vision_tower",
    "mm_projector",
    "Linear(1024->768,bias)",
    "onechart_preproc.bin",
    "onechart_proj_out.bin",
    "onechart_final_logits.bin",
    "proj_out cos 1.00000000",
    "6.5e-4",
    "6.1e-5",
    "argmax 50268",
    "prompt_n",
    "308",
    "D6/D7/D8",
    "D4-prefill",
    "D4 prefill half 1",
    "D4 cached decode",
    "ChartResult",
    "OcrTask::ChartData",
    "model_spec_is_knowably_not_onechart",
    "forward_onechart",
    "chart-data",
    "onechart_chart_e2e/v1",
    "scripts/onechart_chart_e2e.sh",
    "corpus_quality_scrm_proxy",
    "reliable_distance",
    "6/6",
    "0.015",
    "1/6",
    "complete_json_string",
    "prefill_final_hidden",
    "recognize_reads_the_committed_chart",
    "reliable_check_matches_upstream_goldens",
    "number_head_matches_golden",
    "chart_prompt_ids_match_oracle_l0c",
    "DecoderFamily::Opt",
    "DecoderConfig::onechart",
    "opt_prefill_matches_torch_oracle",
    "opt_kvcache_matches_greedy_and_oracle",
    "generate_greedy_kvcache",
    "GotDecodeWeights",
    "MlpW::ReluFc",
    "family_norm",
    "24-token",
    "12-token",
    "13-step",
    "dict-open",
    "onechart.int8.focrq",
    "same-quantization",
    "committed-closed",
    "nn::relu",
    "PretokScheme::Gpt2",
    "Tokenizer::from_opt_dir",
    "vocab.json",
    "merges.txt",
    "added_tokens.json",
    "model_id=onechart",
    "implemented=false",
    "implemented=true",
    "72 int8",
    "29/29",
    "<imgpad>",
    "<Number>",
    "committed-certified",
    "focr pull onechart",
    "TrOMR",
    "Polyphonic-TrOMR",
    "tromr",
    "OP-TM",
    "bd-3jo6.5.2",
    "bd-3jo6.5.3",
    "bd-3jo6.5.6",
    "c22b047",
    "7464590",
    "6403d4c",
    "45da3a3",
    "3472c1b",
    "bd-3jo6.5.4",
    "bd-3jo6.5.5",
    "bd-3jo6.5.7",
    "bd-3jo6.5.8",
    "bd-3jo6.5.9",
    "bd-3jo6.5.10",
    "79d715c",
    "78a2de3",
    "2cbded9",
    "fc9d88a",
    "752f3cd",
    "9127676",
    "ab0bae0",
    "tromr_page_detects_and_reads_stacked_examples",
    "tromr_alpha_ink_path_fires_only_when_alpha_varies",
    "bd-2sez",
    "5430e2c",
    "G2-tromr-f32-staff1-20260706",
    "bd-av64.12",
    "bd-223.2",
    "59d376b",
    "FOCR_THREADS",
    "FOCR_TIMING",
    "sam.hydrate",
    "sam.block attn(GLOBAL)",
    "sam.block attn(win)",
    "sam.block mlp",
    "thread_budget",
    "request_shutdown",
    "shutdown_requested",
    "reset_shutdown",
    "cancel_checkpoint",
    "stream_pages",
    "robot `threads`",
    "FOCR_FORCE_ARCH",
    "scalar|sdot|smmla|avx2|avxvnni|avx512vnni",
    "robot_schema_v1.json",
    "docs/TEST_LOGGING.md",
    "tests/fixtures/test_log_schema.json",
    "skip-with-SUCCESS",
    "native_path_ran",
    "bd-zc1o",
    "bd-n68o",
    "bd-29wv",
    "bd-re8.7",
    "bd-3kge",
    "bd-2pgf",
    "3e85c7d",
    "assert_deterministic",
    "assert_outputs_deterministic",
    "tests/fixtures/PROVENANCE.md",
    "tests/fixtures/MANIFEST.toml",
    "scripts/check_fixture_manifest.py",
    "regenerated-committed",
    "UPDATE_GOLDENS",
    "UPDATE_GOLDENS=1",
    "OP-DG",
    "bd-re8.12",
    "bd-re8.9",
    "bd-re8.10",
    "bd-re8.11",
    "bd-re8.19",
    "fb52843",
    "c685818",
    "390d05c",
    "5f2d7ce",
    "f879211",
    "1b84428",
    "1112cf8",
    "ConformanceTest",
    "RequirementLevel",
    "ConformanceCategory",
    "conformance_registry",
    "tests/conformance_matrix.rs",
    "docs/truth-pack/EXISTING_UNLIMITED_OCR_STRUCTURE.md",
    "SPEC-NNN",
    "MUST coverage",
    "0.95",
    "XFAIL",
    "DISC-NNN",
    "OP-CM",
    "OP-DF",
    "OP-MR",
    "OP-GA",
    "OP-LS",
    "OP-ZM",
    "OP-DR",
    "OP-RT",
    "OP-SG",
    "OP-PS",
    "bd-wp8.4",
    "bd-wp8.4.1",
    "25eadc5",
    "focr doctor",
    "focr doctor capabilities --json",
    "robot-docs",
    "actions.jsonl",
    ".doctor/lock",
    "tests/doctor_fixtures.rs",
    "bd-wp8.7",
    "055e513",
    "focr robot triage",
    "robot_triage_payload",
    "quick_ref",
    "recommendations",
    "docs/ergonomics/AUDIT.md",
    "tests/agent_ergonomics_regression.rs",
    "bd-wp8.8",
    "bd-wp8.10",
    "bd-wp8.9",
    "2bdccc5",
    "scripts/gauntlet_cert.py --release-readiness",
    "scripts/gauntlet_cert.py --bundle",
    "docs/gauntlet/RELEASE_READINESS.json",
    "franken_ocr.release_readiness.v1",
    "certification_bundle",
    "gauntlet_convergence",
    "ship:true",
    "green:13",
    "red:0",
    "certified:true",
    "FINAL_GAUNTLET_REPORT.md",
    "certification_bundle.json",
    "release_certificate.json",
    "scorecards.json",
    "benchmark_summary.json",
    "rounds=11/10",
    "tail_clean=True",
    "bd-av64.11",
    "11f60ea",
    "9546571",
    "5679268",
    "b3f74b6",
    "content_rotation",
    "--pages",
    "--split-spreads",
    "--extract-figures",
    "split_spread",
    "differential_per_op_vs_bf16_oracle",
    "differential_row",
    "EngineIdentity",
    "tests/metamorphic.rs",
    "MR-1",
    "MR-5",
    "tests/fixtures/golden/PROVENANCE.md",
    "docs/conformance/GOLDEN.md",
    "tests/cli_robot_golden.rs",
    "scripts/ladder_scorecard.sh",
    "focr-ladder-scorecard/v1",
    "not_meaningful",
    "skipped_no_model",
    "all_green",
    "OP-BG",
    "OP-VG",
    "bd-223.4",
    "03eadd2",
    "d52d344",
    "RunStore",
    "RunRecord",
    "FOCR_RUN_STORE",
    "focr runs",
    "focr sync",
    "focr sync export-jsonl",
    "focr sync import-jsonl",
    "export-jsonl",
    "import-jsonl",
    "fsqlite",
    "SCHEMA_VERSION",
    "_meta",
    "schema_version",
    "model_version_tag",
    "runs.db",
    "jsonl.lock",
    "jsonl.tmp",
    "best-effort",
    "OP-RS",
    "tromr.focrq",
    "tromr.int8.focrq",
    "model_id=tromr",
    "MusicVocab",
    "MusicTokenizer",
    "WordLevel",
    "tokenizer_rhythm.json",
    "tokenizer_pitch.json",
    "tokenizer_lift.json",
    "tokenizer_note.json",
    "detokenize_goldens.json",
    "group_norm",
    "tf_same_pad",
    "max_pool2d",
    "fuse_relu",
    "TromrEncoderW",
    "tromr_encoder_matches_torch_oracle",
    "tromr_oracle_fixtures.json",
    "encoder_out cos 1.00000000",
    "3.8e-6",
    "TromrDecoderW",
    "decoder_forward",
    "tromr_decoder_matches_argmax_oracle",
    "42-step",
    "7.6e-6",
    "merge_semantic",
    "semantic_to_musicxml",
    "MusicResult",
    "forward_tromr",
    "tromr_staff_tensor",
    "preprocess::tromr_staff_tensor",
    "staff_detect",
    "detect_staves",
    "recognize_page",
    "PageRecognition",
    "StaffSkip",
    "MusicPageMeta",
    "take_music_page_meta",
    "OcrModel::take_music_meta",
    "OcrEngine::take_music_page_meta",
    "robot::staff_event",
    "music_meta_to_json",
    "event kind staff",
    "staff_event_shapes_ok_and_skipped",
    "music_meta_json_interleaves_in_detection_order",
    "schema_advertises_all_events",
    "--json staves",
    "per-staff dims/outcome",
    "staves_to_musicxml",
    "model_spec_is_knowably_not_tromr",
    "scripts/tromr_music_e2e.sh",
    "tromr_music_e2e/v1",
    "missing-model exit 3",
    "wrong-family exit 2",
    "single-staff images",
    "E5 v1",
    "e8_single_staff_quality",
    "full_page_runtime_wiring",
    "DISC-004",
    "tromr_ser_vs_committed_ground_truth",
    "FOCR_TROMR_SEED",
    "0.211",
    "0 int8",
    "scripts/smolvlm2_convert_e2e.sh",
    "FOCR_SMOLVLM2_MODEL",
    "FOCR_SMOLVLM2_ORACLE_HIDDEN0",
    "FOCR_SMOLVLM2_ORACLE_LOGITS",
    "scripts/gen_smolvlm2_token_id_fixtures.py",
    "tests/fixtures/tokenizer_smolvlm2/expected.json",
    "128/128",
    "5ece781d",
    "49190",
    "49279",
    "vision_siglip.rs",
    "token_compress.rs",
    "scripts/gen_reference_fixtures_smolvlm2_vision.py",
    "vision_oracle_fixtures.json",
    "sample_photo.png",
    "13 preprocessed",
    "n_image_slots=832",
    "smolvlm2_pixel_values.bin",
    "smolvlm2_vision_post_ln.bin",
    "smolvlm2_pixel_shuffle_out.bin",
    "smolvlm2_connector_out.bin",
    "gelu_tanh",
    "pixel_shuffle",
    "ft-kernel-cpu",
    "DISC-002",
    "0.998301",
    "scripts/spec_gate_e2e.sh",
    "scripts/gauntlet_runbook.sh",
    "FOCR_SPEC_E2E_IMAGES",
    "SMOLVLM2_SAFETENSORS",
    "dirty-worktree",
    "git diff --stat",
    "live-WIP",
    "d25dbd7",
    "got.hydrate(batch)",
    "got.vision+splice(batch of N)",
    "14.47s",
    "13.53s",
    "~6.5%",
    "FOCR_FIXTURES_DIR",
    "FOCR_STAGE_BUDGET_FORWARD_MS",
    "FOCR_TROMR_SAMPLE",
    "FOCR_TROMR_SEED",
    "PreprocessOverrides",
    "--base-size",
    "--image-size",
    "--crop-mode gundam",
    "Gundam",
    "7 views",
    "CER 0.0179",
    "WER 0.0138",
    "489 tensors",
    "224 int8",
    "265 F32",
    "quiet-host",
    "HF baseline",
    "decode-per-token",
    "A11 zoo",
    "3.37x",
    "2.58x",
    "1.67x",
    "ad3ad20",
    "robot selftest.models",
    "got-ocr2:overflow_k2816",
    "smolvlm2:overflow_k2560",
    "onechart:overflow_k3072",
    "selftest_reports_a_per_model_verdict_for_every_registered_decoder",
    "conformal ratchet",
    "Ville e-process",
    "capacity_certificate_bounded_stream_soak",
    "1.62x",
    "page_0009",
    "page_0014",
    "CER 0.00943",
    "CER 0.03529",
    "0.916",
    "aarch64+neon+dotprod",
    "--f32",
    "crop mode is `base`",
    "B8",
    "B11",
    "2.5%",
    "scripts/got_cer.py",
    "bd-3bom",
    "bd-2dlz",
    "487 s -> 41 s",
    "23.9",
    "64.7",
    "35.93 s -> 16.6 s",
    "lm-head pretranspose",
    "top-256 f32 refine",
    "688/688",
    "kvcache_greedy_matches_oracle_l4",
    "bd-e4yr",
    "bd-34zu",
    "FOCR_GOT_MODEL",
    "FOCR_GOT_TIKTOKEN",
    "FOCR_ORACLE_IMAGE",
    "FOCR_ORACLE_HIDDEN0",
    "implemented",
    "PdfPages",
    "JPXDecode",
    "JBIG2Decode",
    "ARM64 Windows",
    "scanned PDFs",
    "rasterize",
    "NotImplemented",
    "OcrEngine::recognize_with_model",
    "OcrEngine::recognize_batch",
    "ROBOT_SCHEMA_VERSION",
    "FOCR_MODEL_PATH",
    "FOCR_MODEL_DIR",
    "FOCR_QUANT",
    "FOCR_INSTALL_BASE_URL",
    "FOCR_BATCH_SPINE",
    "FOCR_BATCH_PACK",
    "FOCR_DECODE_INT8",
    "FOCR_GOT_INT8_LMHEAD",
    "FOCR_GOT_SEQ_ATTN",
    "FOCR_QKV_FUSED",
    "FOCR_FUSE_NGRAM_LMHEAD",
    "FOCR_SPEC_DECODE",
    "FOCR_SPEC_VERIFY",
    "FOCR_INT8_ATTN",
    "FOCR_INT8_LMHEAD",
    "FOCRQ\\0",
    "R-SWA",
    "MoE",
    "Baidu Unlimited-OCR",
    "scripts/check.sh",
    "tests/cli_robot_golden.rs",
    "tests/e2e_recognize.rs",
    "tests/installer_e2e.sh",
    "docs/NEGATIVE_EVIDENCE.md",
    "When-to-Use Triggers",
    "Failure Modes",
    "Prompt Module",
    "Canonical tag",
    "Evidence anchors",
    "Default Answer Shape",
    "OP-LC",
    "OP-LQ",
    "OP-ST",
    "OP-SV",
]


def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        fail(f"missing {path}")


def markdown_anchor(heading: str) -> str:
    text = re.sub(r"`([^`]*)`", r"\1", heading.strip().lower())
    text = re.sub(r"<[^>]+>", "", text)
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"\s+", "-", text).strip("-")
    return text


def markdown_anchors(text: str) -> set[str]:
    anchors: set[str] = set()
    for line in text.splitlines():
        match = re.match(r"#{1,6}\s+(.+?)\s*$", line)
        if match:
            anchors.add(markdown_anchor(match.group(1)))
    return anchors


def validate_markdown_anchors(path: Path, text: str) -> None:
    anchors = markdown_anchors(text)
    for target in re.findall(r"\]\(#([^)]+)\)", text):
        if target not in anchors:
            fail(f"{path.name} links to missing heading anchor #{target}")


def validate_local_markdown_links(path: Path, text: str) -> None:
    for raw_target in re.findall(r"\[[^\]]+\]\(([^)]+)\)", text):
        target = raw_target.strip()
        if not target or "://" in target or target.startswith(("mailto:", "tel:")):
            continue
        if target.startswith("#"):
            continue

        file_part, _, anchor = target.partition("#")
        linked_file = (path.parent / file_part).resolve()
        if not linked_file.exists():
            fail(f"{path.name} links to missing local file {target}")
        if anchor:
            linked_text = read(linked_file)
            if anchor not in markdown_anchors(linked_text):
                fail(f"{path.name} links to missing local anchor {target}")


def normalize_yaml_scalar(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        return value[1:-1]
    return value


def validate_agent_triggers(path: Path, text: str) -> None:
    seen: dict[str, int] = {}
    in_triggers = False
    for lineno, line in enumerate(text.splitlines(), start=1):
        if re.match(r"^triggers:\s*$", line):
            in_triggers = True
            continue
        if in_triggers and line and not line.startswith((" ", "\t")):
            break
        if not in_triggers:
            continue

        match = re.match(r"\s+-\s+(.+?)\s*$", line)
        if not match:
            continue
        trigger = normalize_yaml_scalar(match.group(1))
        if trigger in seen:
            fail(
                f"{path.name} duplicates trigger {trigger!r} "
                f"at lines {seen[trigger]} and {lineno}"
            )
        seen[trigger] = lineno


def validate_skill(root: Path) -> None:
    skill = root / "SKILL.md"
    body = read(skill)
    validate_markdown_anchors(skill, body)
    validate_local_markdown_links(skill, body)

    if not body.startswith("---\n"):
        fail("SKILL.md must start with YAML frontmatter")

    if "\ndescription: >-\n" not in body:
        fail("frontmatter must use folded description")

    frontmatter = body.split("---", 2)[1]
    if "Use when" not in frontmatter:
        fail("description must include an explicit Use when trigger")
    desc_lines = []
    capture = False
    for line in frontmatter.splitlines():
        if line == "description: >-":
            capture = True
            continue
        if capture and line.startswith("  "):
            desc_lines.append(line.strip())
            continue
        if capture:
            break
    description = " ".join(desc_lines)
    if len(description) > 200:
        fail(f"description is too long for reliable triggering: {len(description)} chars")

    if "focr" not in frontmatter or "OcrEngine" not in body:
        fail("skill must mention both focr and OcrEngine")

    line_count = len(body.splitlines())
    if line_count > 2200:
        fail(f"SKILL.md is too long for an entrypoint: {line_count} lines")

    refs_dir = root / "references"
    all_text = body
    for name in REQUIRED_REFS:
        ref = refs_dir / name
        text = read(ref)
        validate_markdown_anchors(ref, text)
        validate_local_markdown_links(ref, text)
        all_text += "\n" + text
        rel = f"references/{name}"
        if rel not in body:
            fail(f"SKILL.md does not link {rel}")
        if len(text.splitlines()) > 100 and "Table of Contents" not in text:
            fail(f"{name} is over 100 lines and needs a Table of Contents")

    script = root / "scripts" / "validate.py"
    script_text = read(script)
    if not script_text.startswith("#!/usr/bin/env python3"):
        fail("validator must keep its shebang")

    self_test = root / "SELF-TEST.md"
    self_test_text = read(self_test)
    if "current `focr pull`" not in self_test_text:
        fail("SELF-TEST.md must assert current pull support")
    all_text += "\n" + self_test_text

    agent = root / "agents" / "openai.yaml"
    agent_text = read(agent)
    if "franken_ocr" not in agent_text or ".focrq" not in agent_text:
        fail("agents/openai.yaml must route franken_ocr and .focrq tasks")
    if "interface:" not in agent_text or "default_prompt:" not in agent_text or "$focr" not in agent_text:
        fail("agents/openai.yaml must expose interface metadata with a $focr default prompt")
    if re.search(r"(?m)^\s+-\s+\d+\s*$", agent_text):
        fail("agents/openai.yaml trigger values that are all digits must be quoted strings")
    validate_agent_triggers(agent, agent_text)
    all_text += "\n" + agent_text

    for pattern, message in FORBIDDEN_PATTERNS:
        if re.search(pattern, all_text):
            fail(f"stale command form found: {message}")
    for term in REQUIRED_TERMS:
        if term not in all_text:
            fail(f"missing current focr feature coverage: {term}")


def main(argv: list[str]) -> int:
    root = Path(argv[1]) if len(argv) > 1 else Path(__file__).resolve().parents[1]
    validate_skill(root)
    print("OK: focr skill validates")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
