// focr_ios.h — the C ABI for the franken_ocr engine on Apple platforms.
//
// Hand-written and checked in (the modulemap beside it is generated by
// ios/build-rust.sh). Keep this in lockstep with focr-ios/src/lib.rs; the Swift
// side sees ONLY what is declared here.
//
// ── Contract ───────────────────────────────────────────────────────────────
//
// Errors.  Functions returning int32_t use 0 for success and a nonzero
// franken_ocr exit code for failure (2 usage, 3 model_not_found, 4
// input_decode, 5 timeout, 6 cancelled, 7 format_mismatch, 1 generic).
// Functions returning a pointer use NULL for failure. After ANY failure,
// focr_last_error_message() returns a human-readable reason for the calling
// thread. It never returns NULL; before the first failure on that thread it
// returns an empty string.
//
// Strings.  Every `char *` returned through an out-parameter is owned by the
// caller and must be released with focr_string_free(). Every `const char *`
// returned directly is owned by the library, is valid until the next call that
// replaces it on the same thread, and must NOT be freed.
//
// Bytes.  Buffers returned through (uint8_t **out, size_t *out_len) are owned
// by the caller and must be released with focr_bytes_free(ptr, len), passing
// back the EXACT length that was returned.
//
// Threading.  A FocrEngine is NOT thread-safe. Serialize all access to one
// engine (an actor is the intended mechanism). The progress callback is invoked
// from whichever thread is running the forward, which is never the main thread;
// it must be safe to call from any thread and must not block.
//
// Panics.  The release profile is `panic = "abort"`, so a panic cannot unwind
// across this boundary. Every entry point additionally catches unwinds so debug
// and test builds stay sound.

#ifndef FOCR_IOS_H
#define FOCR_IOS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// Opaque handle to a loaded model. Create with focr_engine_open, release with
// focr_engine_close. Closing NULL is a no-op.
typedef struct FocrEngine FocrEngine;

// ── Diagnostics ────────────────────────────────────────────────────────────

// The calling thread's last error. Never NULL; empty before any failure.
// Owned by the library; do not free.
const char *focr_last_error_message(void);

// One JSON object describing the build and this device's dispatch:
// {"crate_version","detected_tier","dense_route","threads","project_license"}.
// `detected_tier` is the hardware capability; `dense_route` is what ordinary
// dense int8 GEMM will ACTUALLY execute — they differ on Apple silicon by
// design, and reporting only one of them would overclaim. Owned by the library.
const char *focr_engine_info_json(void);

// Re-run the dispatched int8 GEMM against the bit-identical scalar oracle on
// THIS device, including the worst-case K=6848 i32-accumulation row, and write
// one JSON verdict to *out_json (caller frees with focr_string_free).
// Returns 0 when every case matched AND every call executed the selected route.
// This is the shippable proof for a device the binary was never built on.
int32_t focr_selftest_json(char **out_json);

// Width of the kernel thread pool actually in force. Calling this installs the
// pool if it is not yet installed, so call it once at launch if you want the
// pool built before the first (long) forward rather than during it.
size_t focr_kernel_pool_width(void);

// ── Engine lifecycle ───────────────────────────────────────────────────────

// Load the model artifact at `artifact_path` (UTF-8, NUL-terminated).
// Tokenizer sidecars are resolved from beside the artifact. Returns NULL on
// failure. On iOS the artifact is memory-mapped by default, so this call is
// fast and its cost is paged in lazily during the first forward.
FocrEngine *focr_engine_open(const char *artifact_path);

// Release the engine and its caches. Safe to call with NULL.
void focr_engine_close(FocrEngine *engine);

// Registry id of the loaded model ("unlimited-ocr", "tromr", ...). Owned by the
// library, valid until the engine is closed.
const char *focr_engine_model_id(const FocrEngine *engine);

// The license notice that must travel with this artifact. Owned by the library,
// valid until the engine is closed.
const char *focr_engine_license(const FocrEngine *engine);

// ── Recognition ────────────────────────────────────────────────────────────

// Recognize one encoded image (PNG/JPEG bytes) and write a JSON envelope to
// *out_json (caller frees with focr_string_free):
//
//   {"model_id": "...",
//    "output": "<markdown, or MusicXML for TrOMR>",
//    "layout": [{"label": "...", "boxes": [[x1,y1,x2,y2], ...]}],
//    "music": {"staves":[...], "skips":[...], "warnings":[...]} | null,
//    "tall_strip_count": 4 | null,
//    "low_yield": {"yield_chars":14, "input_megapixels":0.988} | null}
//
// `layout` mirrors `focr ocr --json`. The default Unlimited-OCR model routes
// images at least 3x taller than wide through the CLI's same smart-cut strip
// path; specialty models remain one-pass. `low_yield` is an honest warning
// that a page-sized input produced almost no text, not a recognition failure.
// This is a long blocking call — minutes for a document page. Do not call it
// on the main thread.
int32_t focr_recognize_json(FocrEngine *engine, const uint8_t *image_bytes,
                            size_t image_len, char **out_json);

// ── Progress and cancellation ──────────────────────────────────────────────

// Progress callback. `stage` is one of "preprocess", "vision", "prefill",
// "decode", "postprocess", "staff" and is valid ONLY for the duration of the
// call — copy it if you need to keep it. `total == 0` means indeterminate.
// Invoked from the forward's own thread; must be non-blocking and thread-safe.
typedef void (*FocrProgressFn)(void *ctx, const char *stage, uint64_t current,
                               uint64_t total);

// Install (fn != NULL) or clear (fn == NULL) the progress callback. `ctx` is
// passed back unchanged. The caller guarantees `ctx` outlives the callback,
// i.e. clear it before releasing whatever `ctx` points at. Clearing or replacing
// from another thread waits for any active callback to return; a callback may
// also clear itself reentrantly.
void focr_set_progress_callback(FocrProgressFn fn, void *ctx);

// Cooperative cancellation. A running forward observes the request at its next
// checkpoint and fails with exit code 6. Reset before starting new work.
void focr_request_cancel(void);
void focr_reset_cancel(void);

// ── PDF ────────────────────────────────────────────────────────────────────
//
// A PDF is opened ONCE and rendered many times. Parsing is not free — a scanned
// book is tens of megabytes of object graph — so a render-by-bytes API would
// re-parse the whole document for every page, which is exactly the wrong shape
// for the common case of "OCR this entire 300-page scan".

// Opaque handle to an opened PDF.
typedef struct FocrPdf FocrPdf;

// Parse a PDF held in memory. The bytes are copied into an owned document, so
// the caller may release them as soon as this returns. NULL on failure.
FocrPdf *focr_pdf_open(const uint8_t *pdf_bytes, size_t pdf_len);

// Release the document. Safe to call with NULL.
void focr_pdf_close(FocrPdf *pdf);

// Number of pages. Returns 0 for a NULL handle.
uint32_t focr_pdf_page_count(const FocrPdf *pdf);

// Rasterize one 1-based page to PNG bytes (caller frees with focr_bytes_free).
// Pages whose codec has no pure-Rust decoder (JPEG 2000, JBIG2) and born-digital
// vector pages fail with a message naming exactly what was unsupported, rather
// than returning a wrong result — so a caller walking a whole document can skip
// that page with a reason and keep going.
int32_t focr_pdf_render_page(const FocrPdf *pdf, uint32_t page,
                             uint8_t **out_png, size_t *out_len);

// ── Decode options ─────────────────────────────────────────────────────────
//
// The library reads these from environment variables on desktop. An app has no
// environment worth speaking of, so they are setters — the same seam focr-wasm
// exports for the browser.

// Sliding no-repeat n-gram guard. 0 disables it. Hard dense scans can tip the
// decode into a repetition loop; the manifest ships a per-model value.
void focr_set_no_repeat_ngram(uint32_t n);

// GOT-OCR2 "OCR with format:" structured mode (LaTeX / tables / molecules /
// geometry / sheet music).
void focr_set_got_format(bool on);

// SmolVLM2 describe/VQA question. Empty string restores the model-card caption
// prompt.
void focr_set_smolvlm2_question(const char *question);

// ── Memory ─────────────────────────────────────────────────────────────────

void focr_string_free(char *s);
void focr_bytes_free(uint8_t *ptr, size_t len);

#ifdef __cplusplus
}
#endif

#endif // FOCR_IOS_H
